### ISSUE TITLE
Akashic tome deletes specific books

### ISSUE THREAD

**Issue by collosiskdway** [AllTheMods/ATM-6#1076]
I do not know the full details but books like the astral sourcery book and the powah manual are deleted from the akashic tome when you try to open them.

**Comment by TBoshoven** [comment]
I think this happened during a mod update.
I also had those exact books disappear after updating to 1.5.2 from 1.5.0, accompanied by a game crash.
One of my other books also lost its name until I switched to it and back.

When I got back in after the crash, I cheated the books back in, added them back to my Akashic Tome and everything worked fine since then.
My Astral Tome even still had the papers in it.

**Comment by DaveJK** [comment]
Akashic Tomes was updated in 1.5.2 and do not work with the old Akashic Tome from previous versions. Delete the old book, create a new one.
