### ISSUE TITLE
Question regarding Resourceful Bees pathfinding. ATM6 1.5.2

### ISSUE THREAD

**Issue by RodrigDuarte** [AllTheMods/ATM-6#1106]
I have built several apiaries on the desert and I put a sandy bee inside one, but she sticks to the walls to try and go pollinate the sand outside when she has one sand block inside the structure.
Is there a way to fix this pathing issue?
ATM6 1.5.2
![image](https://user-images.githubusercontent.com/52805238/108611990-3b4f8a80-73dc-11eb-91c0-9461d9ec30a0.png)

**Comment by Pdiddy973** [comment]
This should be fixed in a coming update to resourceful bees, but for now you can pick up the bee and import it into the apiary, and when it leaves it will have a chance to forget the "flower" block when it leaves the apiary

The update coming for bees should make it so the bee will reset the hive and flower position when it leaves the jar.
