### ISSUE TITLE
Faes from Mahou Tsukai doesnt spawn - 1.5.2

### ISSUE THREAD

**Issue by Knale44** [AllTheMods/ATM-6#1108]
Hello,

I'm trying to find some Fae, but i can't. I used the scroll from de mod, follow a lot of different leylines but i can't find a single Fae.

**Comment by stepsword** [comment]
1) Find a leypoint (where leylines intersect) with 3 rings around it.
2) Stand right in the middle of it.
3) Make sure your mana is less than your max mana.
4) Every 5 seconds, there is approximately a 10% chance of a Fae spawning at your Y level within 10 blocks. The more open air near you, the closer to 10% it will be.
5) Turn your sound on so you can hear the bells when a Fae spawns, then use Mystic Eyes of Fay Sight to be able to see them.
Bonus: Caliburn and Morgan are much better at hitting Fae since they have builtin sweep attacks.

**Comment by Knale44** [comment]
Thank you very much.
