### ISSUE TITLE
[1.5.2] Ender Beecon causes massive FPS lag

### ISSUE THREAD

**Issue by nddragoon** [AllTheMods/ATM-6#1135]
**Describe the bug**
Placing and looking at an Ender Beecon from resourceful bees tanks my FPS by more than half. Seems to only happen when it's on since FPS were fine when it was not getting enough honey

**To Reproduce**
Place an Ender beecon and provide it with RB honey

**Screenshots**
https://streamable.com/s2r896

**Comment by Pdiddy973** [comment]
Do you have performant or optifine added to the pack? Or anything else? If so can you try with the base pack

**Comment by nddragoon** [comment]
I added performant yesterday to try and fix it cause i thought it might be the bees themselves, but yes it happens without performant and optifine

**Comment by Pdiddy973** [comment]
Can you make a gif w/o optifine or prefomant.

**Comment by nddragoon** [comment]
[Here you go](https://streamable.com/tkj87s). took out performant. my overall FPS are slightly worse but the way the FPS tank as soon as i place it is still quite visible

**Comment by Pdiddy973** [comment]
try and update to 1.5.6 and see if issue persists

**Comment by Kipex** [comment]
I just realized this was why my base was so laggy. I'm running the latest version 0.6.5b of Resourceful Bees and this is still very much the case for me as well. The moment I place the beecon down and have it active with honey, my FPS drops by 40. No difference whether I have the beam and sound active or not.

We're still using ATM6 1.5.5 otherwise, but had to update Resourceful Bees because of another bug.

**Comment by Nidaelie** [comment]
Hello playing atm6 1.6.2 and beecon causeing 20 frames drop... i activete it -20 frames, i disable it normal frames....
