### ISSUE TITLE
Increase the energy capacity of RS controllers

### ISSUE THREAD

**Issue by nddragoon** [AllTheMods/ATM-6#1152]
**Is your feature request related to a problem? Please describe.**
RS creative controllers don't actually have infinite power, but a 32krf buffer that refills every tick. This means one can only have a network that consumes that much before the system shuts down. 2 of the infinite range upgrades for wireless transmitters alone consume more than 32krf/t, making them effectively pointless.

**Describe the solution you'd like**
Increase the energy capacity of RS controllers

**Additional context**
![image](https://user-images.githubusercontent.com/54559451/109573061-ee427700-7ab3-11eb-9476-d66fc6ab7662.png)

**Comment by sciguyryan** [comment]
This seems like a good idea (and changing the config option is easy) but I see an issue with doing so.

That would not alter the alter the capacity of all controllers, not just the creative one. This means that they would act as a considerably power sink if a large figure is used. This could prove to be an issue, especially early game.

The simplest fix would be for Refined Storage to make it so that the buffer is simply ignored when dealing with a creative controller. It might not have crossed their minds as they are not intended for use in survival.

**Comment by starforcraft** [comment]
Use Creative Wireless Transmitter.
