### ISSUE TITLE
Ice and fire balance issues

### ISSUE THREAD

**Issue by HairyHorux** [AllTheMods/ATM-6#1227]
ATM-6 Version 1.5.3

I was going to comment about the lack of dragon spawns in the other, but looking at the patch notes for the most recent release, that hopefully has been fixed.  There are other issues relating to dragons though:
1. Although finding dragons in the other is hopefully now easier, finding the dragon caves is virtually impossible due to the prominance of the blue unblockable lava in the other, which prevents you from mining down once you find a vein, and therefore mining down low enough to (hopefully) find one of the tier 5 dragons that drop dragon eggs.
2. The balancing of the ice and fire mobs in the other is completely off, as for some reason they are all raised to the level of allthemodium weapons and armor and the higher tier ice and fire swords, which means you have to get that stuff to stand a chance of killing any of the mobs, except you can't as you need to fight your way past those mobs to get the weapons needed to kill those same mobs, especially since after the ice and fire mod, the next highest damage weapon does about 25 base damage.
3. Even if you did have the unobtanium sword and armor, the dragon's breath attacks (tested with a tier 3 lightning dragon) do so much damage they chew through ~20-30 hearts (40-60 damage) very quickly, even with a full set of enchanted unobtanium armor.  I think it needs dialing back a little bit (not much, just so that it doesn't instakill you suddenly).
4. This is just a suggestion and you may have already done this, but PLEASE reduce the spawns and range of cockatrices.  You can't do anything in the other without ending up being made nauseous from ~30-40 blocks away and it's just really annoying to have to deal with constantly.
5. It would be great if the allthemodium dimensions could be searched for via the nature's compass, just to make it easier to find the biomes that certain Ice and Fire mobs spawn in.
6. Ghosts.  All of the Ghosts.  They are supposed to despawn/have reduced spawns during daytime, but since The Other is constantly nightime, they NEVER DESPAWN.  And because their health is so high (~1300 ish I think) you 1. can't kill them with normal weapons and 2. can't escape them as they phase through walls.

**Comment by Strange-Account** [comment]
sign

**Comment by Grath** [comment]
1. Spawn rate on dragons is still not particularly great as of 1.5.5; I'm routinely flying thousands of blocks between dragons in The Other. I've never found a dragon cave, even with dipping into spectator mode to xray for them near the roosts.
2-3. I have a sword which is dealing 2,000+ damage (Mahou Tsukai allows as far as I can tell infinite scaling damage on swords) and dragon fights are still hairy with the extreme damage output of breath attacks. Full enchanted Unobtainium armor, 30 hearts, almost die in dragon breath if I let them breathe.
4. I have Shadow Step VII on my boots, which has effectively neutralized the cockatrices; 1.5.4 did improve this slightly, cutting cockatrice health from 4,000 to 1,000, but they're still a pain.
5. Yes, this is absolutely necessary. Scannable mod is also a common suggestion I've seen for being able to ever find the caves, since it can look for chests or the treasure piles.
6. Hasn't been an issue for me, but that's because I leapfrogged weapon damage higher than Dragonsteel (or even SGear Vibranium/Unobtainium alloy weapons)

**Comment by RNJordy** [comment]
Couldn’t agree more. The fact that you need Allthemodium alloys to even have a chance at fighting dragons yet you can’t make them unless you fight dozens and dozens of dragons. It’s completely ass backwards. It’s like saying you need 10 years experience for an entry level job.

Nobody should be quite literally forced to get into Mahou Tsukai in order to continue. It makes the pack feel extremely railroaded. The only way I even have a shadow of a chance against the Other mobs and dragons is because I had alloy tools before this “balance” patch. Even then I die quite frequently even with full enchanted Unobtainium because of the dragon fire. I truly hope they see how crazy this is.

**Comment by thevortex** [comment]
news flash, dragons are tough

**Comment by Grath** [comment]
Cool, fine, dragons are tough. What about being able to find dragon caves in the first place?

**Comment by thevortex** [comment]
A cave is half as likely as a roost as far as spawn chance, the distance
between dangerous worldgen is at about 500 blocks separation distance, the
caves do spawn but it's not something you will be able to speed through,
things like myrmex, hydras and cyclops nearby will affect a dragons chance
of a spawn

**Comment by RNJordy** [comment]
> news flash, dragons are tough

Good to know you didn’t read any of what we’ve been saying. Complete dismissal isn’t a good look when valid criticism is given.

**Comment by thevortex** [comment]
You are free to set the configs however you like if you feel the settings
we ship are not up to your needs

**Comment by RNJordy** [comment]
This doesn’t have anything to do with settings. It’s the progression of the entire pack. Please at least understand the flawed logic. At the moment you are giving us a wall with no door. Yet in order to make a door you need to be on the other side first. You’re putting step 4 in front of step 2 which breaks progression to almost a standstill.

**Comment by thevortex** [comment]
I've watched a great deal of streams and YouTube playthroughs where players
are somehow overcoming this adversity. It is recommended you have minimum
unobtainium gear, highly enchanted.

**Comment by HairyHorux** [comment]
I have unobtanium gear, highly enchanted.  The only way I've found to kill dragons (given that the tier 3 ones have about 32000 health) is to use a mob capture item to dump them into an obsidian or similar cage full of player damage traps and leave them there for about 2 hours.  This is because even with the aforementioned highly enchanted gear I'm still taking about 60hp damage from the dragon breath attacks and have no way of killing them with conventional weapons.  And this is a TIER 3.  There's apparantly another two tiers of dragon but those can only be found in the aforementioned impossible to find caves.  I get that you're trying to turn dragons into some kind of endgame boss but they aren't really fun to fight or actually possible to fight unless you cheese them, and that's not fun to try and do.  

Most of the ice and fire mobs are now basically not worth fighting because the loot that they drop is lackluster compared to the health of the mobs.  I think by the time I (theoretically) find enough dragons and similar to kill that I can make the alloy blade, it'll be worthless because the modpack basically forces you to make a morgan in order to do enough damage to fight the mobs in the other, and therefore by the time you can make the alloy blade it's so weak compared to your morgan that it's not worth the effort of making it.

**Comment by HairyHorux** [comment]
Additional: if you are absolutely dead set on making the Dragons ludicrously powerful, so that you need a ridiculous amount of damage and preparation in order to fight them, at least also then power up the dragon mail and dragon weapons that you can only get by defeating them.  At this point, they feel like "oh, I defeated a legendary dragon, it took me several deaths to do so and several weeks of preparation, let me just make the dragon mail, that I can only get by defeating this legendary creature, to better protect me from the rest of the- oh it's much worse than the armor I already have, by orders of magnitude."

**Comment by RNJordy** [comment]
> I've watched a great deal of streams and YouTube playthroughs where players are somehow overcoming this adversity. It is recommended you have minimum unobtainium gear, highly enchanted.
> […](#)

Most playthroughs I’ve seen are from months ago which didn’t have Allthemodium alloys hidden behind a dragon forge. This requires you to kill dozens of dragons as well as having your own as a pet to power the thing. At that point in progression what is even the point of having the alloys anymore? 

Like I’ve said before, for those of us that started before this change probably have alloys from before the change. But new players are screwed unless they spend hours unlocking Mahou Tsukai and many more hours killing villagers to get the Morgan sword to a high enough level to even stand a chance against dragons.

If it is intended for progression to include the Morgan sword then so be it, but by the time you get a strong enough Morgan sword to make a difference there’s no reason to make the alloy tools. I’m personally not saying the pack is hard. I’m saying it doesn’t make sense in it’s current state.

Either the dragon forge needs to be easier to make or the alloys need their own furnace before you ever enter The Other. For example I’ve killed about 7 dragons so far and I still don’t have enough scales to make a single dragon forge brick. You need like half a stack of bricks to make a forge. Partially because we can’t mix scales to make bricks and the fact that we just don’t get enough scales. 

Now imagine you are a new player that never had access to these strong weapons. That’s the problem.
