### ISSUE TITLE
Bigger Reactors (biggerreactors-1.16.4-0.4.3) has failed to load correctly

### ISSUE THREAD

**Issue by Florek81** [AllTheMods/ATM-6#1243]
**Describe the bug**
See description

Try to load latest ATM6 - 1.16.5-1.5.5
Previous Version: ATM6 - 1.16.5-1.5.3 

**To Reproduce**
1. Start Game
2. Wait while Loading...
3. Get Error Message

**Logs**
https://pastebin.com/KciRYqkE

**Comment by RogueLogix** [comment]
corrected steps to reproduce

install 1.5.3 with curseforge, update to 1.5.3b+ with curseforge, try to load game.

This issue is with the curseforge launcher, not the mod or the modpack. The launcher incorrectly updates leaving behind multiple mod versions and FML attempts to load incompatible versions of BiggerReactors and Phosphophyllite

**Comment by Florek81** [comment]
Ok, didn't work out, so I had to make a new Profile and after that it worked.
Thanks for your help.
