### ISSUE TITLE
Allthemodium/vibranium/unobtanium panels shouldn't be equivelant to existing tiers 6-8

### ISSUE THREAD

**Issue by HexCodeFFF** [AllTheMods/ATM-6#1413]
**Is your feature request related to a problem? Please describe.**
the atm panels are expensive as hell and have literally no use
![image](https://user-images.githubusercontent.com/35177464/114571409-44224700-9c3c-11eb-8bc5-a761e8573ca9.png)
![image](https://user-images.githubusercontent.com/35177464/114571445-4b495500-9c3c-11eb-853d-062cd64fa9e3.png)
you're literally _wasting resources_, if you use a redstone lamp instead of an allthemodium block you get double the power, since ATM panels are equivelant to tiers 6-8. this is stupid,,,

**Describe the solution you'd like**
The ATM panels should be in their own tiers, 9-11, much like the draconic evolution [wyvern](https://ftbwiki.org/Wyvern_Solar_Panel), [draconic](https://ftbwiki.org/Draconic_Solar_Panel), and [chaotic](https://ftbwiki.org/Chaotic_Solar_Panel) panels.

**Describe alternatives you've considered**

**Additional context**
the recipies will probably be need to be made a lot more expensive due to 3 tiers of exponential growth. a hypothetical tier 11 unobtanium panel (equivelant to the [chaotic panel](https://ftbwiki.org/Chaotic_Solar_Panel) would generate half a million FE/t

**Comment by tyler489** [comment]
i Support this.... i have 20 t 8 panels and its not enough atm.

**Comment by Zargachi** [comment]
I also support this change, plus i would like to appoint this error too: the 4096k Fluid Storage Part from Refined Storage also have 2 recipes 1 using allthemodium nuggets and the other using a quartz enriched iron, i don't need to say that using the allthemodium version is unlikely specially because the next tier needs allthemodium.
Also, none of the really end tiers of storage for AE2 have a recipe using the ATM ingots, don't know if this is proposital or not.

**Comment by whatthedrunk** [comment]
We plan to work on these soon. The original recipes were supposed to be removed to only use the atm ones but the mod was bugged but not fixed. Thanks for the suggestion and we'll hopefully get the changes in soon.
