### ISSUE TITLE
[ATM6-1.6.0c] Feral flare lantern places invisible light sources inside Bigger Reactor reactors, breaking them

### ISSUE THREAD

**Issue by RageRaptor** [AllTheMods/ATM-6#1453]
The feral flare lantern from Torchmaster places its invisible light sources inside Bigger Reactors reactors, breaking the reactor multiblock.

**To Reproduce**
1. Build a Bigger Reactors reactor with at least some air "blocks" inside the reactor.
2. Place feral flare lantern nearby the functioning reactor
3. After an undetermined amount of time the reactor multiblock breaks
4. Right-clicking the now unformed reactor structure produces the following chat message: 
> Invalid block (Invisible Light) for interior at (coordinates): 

So far this has only happened to me once, and I haven't been able to reproduce it. The reactor was already built and had run for quite some time before I ever placed the lantern. The lantern doesn't even really seem to have a direct line of sight to the reactor, much less to the inside. I was able to get the reactor multiblock to re-form by replacing all air blocks on the inside of the reactor with a random block (cobblestone) and breaking them again. The following screenshot of the chat messages was taken after I fixed the reactor.

![invisiblelights](https://user-images.githubusercontent.com/17185514/115122696-9a371780-9fb9-11eb-964a-b25283f392fa.png)

**Comment by RogueLogix** [comment]
This is a kinda weird issue that I'm not super inclined to fix right now as "fixing" it has some other weird implications. This specific issue is fixed in 1.17 with the addition of light blocks. ATM can add a specific exemption for this block (and iirc i did direct one of the the team on how, but just ping me on discord to ask, because i dont even remember who i mentioned it to).

Part of the problem here is that even if i were to make the invisible light here act like air, it doesn't really solve the problem of other stuff placing blocks inside the reactor causing this same problem with a different block. The torch charm is a great example of the same problem with a different block that isn't as cut and dry of it it should be ignored like a light block should, so i decided to not "fix" either, and leave it as it is.

I will also note that its not an undetermined amount of time, its when the multiblock validates its structure again. When the multiblock system decides to re-validate is decided under the assumption that only the player will be editing blocks, and that it is impossible to place/break a block inside a reactor/turbine that is assembled without first causing it to be disassembled by breaking an external block. You can force this undetermined time to be almost immediately by breaking and replacing any single block of the reactor. Other ways include leaving the area and coming back, and reloading your world.

My recommended fix for this is to use water (can be flowing) to fill the gaps you have in your reactor, so the dread lantern (and torch charm) wont place anything there.

**Comment by RageRaptor** [comment]
> ATM can add a specific exemption for this block 

Do you mean the 1.17 block here or the invisible light blocks I'm having trouble with?

> just ping me on discord to ask

Do you mean I should or someone from the ATM team?

> I will also note that its not an undetermined amount of time, its when the multiblock validates its structure again. 

Fair enough! I wasn't sure when it happened exactly, my base just lost power all of a sudden and when I checked on the reactor I found it broken. 😂  Thanks for the clarification. 

> My recommended fix for this is to use water (can be flowing) to fill the gaps you have in your reactor, so the dread lantern (and torch charm) wont place anything there.

Sounds simple enough, I'll do that for the time being. Thanks! 😁

**Comment by RogueLogix** [comment]
> Do you mean the 1.17 block here or the invisible light blocks I'm having trouble with?

1.17 isn't here yet, so, the invisible light

> Do you mean I should or someone from the ATM team?

ATM team, if they want this fixed, it can be done, even without me updating BiR

**Comment by RageRaptor** [comment]
👍
