### ISSUE TITLE
1.6.1 Creative Energy Cube not Storing/Sending Energy

### ISSUE THREAD

**Issue by Yassine1338** [AllTheMods/ATM-6#1490]
Same Problem as in: #1467

I plug the cables into the cube and it just eats the energy

**Comment by jombo23** [comment]
If you have the same issue as someone else you should use their same issue page unless you believe its caused by something different.

copy-paste from my post on #1467 

You have to energize it with an ATM star which you can clearly see in the third tab of recipies in JEI else its just an energy sink.
![image](https://user-images.githubusercontent.com/4957057/116003159-dc201900-a5ca-11eb-95a6-be399d7b37f7.png)
