### ISSUE TITLE
Failed to sync registry error on update to 1.6.2 server files.

### ISSUE THREAD

**Issue by LowdenTech** [AllTheMods/ATM-6#1537]
I recently updated my community's server to the 1.6.2 update using the server starter files provided on the CurseForge website. I have an exiting server on 1.5.7 and replaced the config, defaultconfigs, libraries, kubejs, and mods folders. I replaced the forge and serverstarter JAR files. And replaced the server-setup-config.yaml file. After which, the server lunches perfectly fine from my Ubuntu Linux Server with no errors, but when connecting from client provides me with the following message: "Failed to synchronize registry data from server, closing connection". Can anyone advise on what the issue may be?

I performed the same process using a backup of the 1.5.7 server and the 1.6.1 server files and has been running stable so far.

**Comment by twothe** [comment]
We are having the same issue with a LAN multiplayer world. We have removed Chisel & Bits from the list of mods, but while the server can easily join the game, I no longer can. The client logs say I am missing Chisel & Bits mod to join, but neither the server nor I have installed that mod.

So we reinstalled the pack, but while the world is fine on the server, my client now has all blocks randomly swapped around:
![image](https://user-images.githubusercontent.com/1131621/116817963-2aa05b00-ab69-11eb-9432-cdaa2b850071.png)

Note that all the blocks that are not vanilla Minecraft are wrong, it looks entirely different on the server. This is more than a display issue, I can no longer use most functional blocks. Also the situation does not seem to be recoverable, reinstalling, loading backups, nothing helps, client and server are constantly out of sync. We are unable to play with version 1.6.2, 

We tried starting a new world, and that world is actually in sync. So the issue seems to be when updating the world file from a previous version.

**Comment by LowdenTech** [comment]
That's good to know that it works on a fresh install of the server. Might help narrow down where the issue is coming from. Thanks for the info!

**Comment by jmyoung** [comment]
This happened to me too.  World created on 1.6.1, upgraded clients to 1.6.7, world loads OK for the server, but cannot be logged into by any of the clients - they all get 'Failed to sync registry' errors.  Reverting to my 1.6.1 copy works fine.

Bit of a showstopper really :/

**Comment by whatthedrunk** [comment]
This may have been fixed in the newest version of forge that's in the new updates. If you are still having the issue let us know.
