### ISSUE TITLE
Version 1.6.2 Error Loading 3 mods

### ISSUE THREAD

**Issue by willmb** [AllTheMods/ATM-6#1542]
![image](https://user-images.githubusercontent.com/63399435/116588629-29b1c400-a8f2-11eb-86ea-4156991c0a4d.png)

[latest.log](https://github.com/AllTheMods/ATM-6/files/6400316/latest.log)

Updated to 1.6.2 and got those errors.

**Comment by willmb** [comment]
[crash-2021-04-29_14.32.54-fml.txt](https://github.com/AllTheMods/ATM-6/files/6400547/crash-2021-04-29_14.32.54-fml.txt)

**Comment by thevortex** [comment]
this error happens when you update forge to a different version than we ship with the modpack, forge should be 36.1.2 and your logs are showing you changed the version of forge to forge-1.16.5-36.1.13, for at least allthetweaks, updating the mod to 1.3.3 will resolve the issue, but if the other two mods still present this error and have no updates, you will need to revert forge to 36.1.2
