### ISSUE TITLE
Game Crashes after adding resource pack

### ISSUE THREAD

**Issue by Dragonlordhavoc** [AllTheMods/ATM-6#157]
**Describe the bug**
Game Crashes after adding a resource pack to the game, due to Silentgear:grader_catalysts

**To Reproduce**
1. load ATM 6 1.16.3 enter options add a resource pack to the game
2. click done with option changes
3. see game reload then displayes error

**Expected behavior**
Forces game to reload mod textures, near finishing loading mod images crashes due to: java.lang.IllegalStateException: Tag silentgear:grader_catalysts used before it was bound

**Screenshots**
![image](https://user-images.githubusercontent.com/33767854/95663791-a07aa180-0b07-11eb-8775-41cfa45d4427.png)

**Additional context**
[crash-2020-10-10_14.45.15-client.txt](https://github.com/AllTheMods/ATM-6/files/5359905/crash-2020-10-10_14.45.15-client.txt)

**Comment by WhitePhant0m** [comment]
Update SGear or wait for a pack update that includes the updated version

**Comment by Dragonlordhavoc** [comment]
the Problem continues with other mods when I removed Silentgears mods so I pretty sure it has something to do with the 2 outdates textures that are in the pack you can not remove

**Comment by Felilang** [comment]
I have a similar Issue, when I load an Ressource Pack. I have an Nullpointer Exception. 
![minecraft](https://user-images.githubusercontent.com/4568569/95886448-e1c8b680-0d7e-11eb-8f5b-3bd652cd381c.PNG)

Additional context
[crash-2020-10-13_17.34.15-client.txt](https://github.com/AllTheMods/ATM-6/files/5372615/crash-2020-10-13_17.34.15-client.txt)

**Comment by boneys26** [comment]
Same issue as Felilang, I get it when I change graphic settings and when I try to activate my resource pack.

**Comment by htmlordplays** [comment]
![Capture](https://user-images.githubusercontent.com/73088182/96394322-aae40d80-118f-11eb-93d4-539beec0b004.JPG)
The issue is due to load order on the Resource Packs.  Make sure your graphical resource pack is as far down the list as possible (but above Default).  My testing shows it *must* be below resources.zip and KubeJS and it may be the case that it must be below Modresources (but I can't confirm that at this time for all packs).

**Comment by robsonld04** [comment]
> ![Capture](https://user-images.githubusercontent.com/73088182/96394322-aae40d80-118f-11eb-93d4-539beec0b004.JPG)
> The issue is due to load order on the Resource Packs. Make sure your graphical resource pack is as far down the list as possible (but above Default). My testing shows it _must_ be below resources.zip and KubeJS and it may be the case that it must be below Modresources (but I can't confirm that at this time for all packs).

Tried this and still the same crash. Noticed a few people are playing with resource packs so what are they doing different?

**Comment by ViRb3** [comment]
As mentioned in the issue linked above, have you tried with Optifine REMOVED?

**Comment by Marcel40625** [comment]
You need to add the ressourcepack via options.txt and launch with it, trying to change it ingame always crashed on me with or without optifine, now the only problem is that textures for the mods not working ...

**Comment by NetMasterFlex** [comment]
If editing options.txt doesn’t work. Try the following that has been my go to since 1.3.4 and hast failed yet. Step 1. Load game to main menu. Step 2.  Click “Options” Step 3 click “Resource Packs”. Step 4. Move your resource pack from left to right side of screen. I move both Quark texture and my resource pack. They are listed at the top which has worked fine. Step 5 click “Done”.  Note: the screen will freeze for a moment until you see the Mojang loading screen with yellow bar. Step 6. Click the X in the corner of the loading page to close the game completely. Step 7. Reload the game. 
If all goes well, your texture pack should be applied. You can verify via steps 1 thru 3 or just join a single player or server. Your game should work with texture applied.  If this doesn’t work, I’m out of ideas. 

NMF
