### ISSUE TITLE
ResourcefulBees

### ISSUE THREAD

**Issue by piaoff** [AllTheMods/ATM-6#1617]
ResourcefulBees - Dragonic bee does not mutate to allthemodium bee

**Comment by Letziah** [comment]
Wither bee appears to be broken as well (not mutating). Besides that, wither honeycombs are not being processed in the centrifuge (recipe is missing in JEI).

**Comment by lazystudent3** [comment]
@Letziah  I am playing on 1.6.3c version of pack and have no problems with wither honeycombs processing and I have recipe in JEI.  

@piaoff  I also have problem with Dragonic Bee. and in my case its that "flower" for Dragonic Bee is missing from JEI as well as from beepedia (There is blank space) 

![bug3](https://user-images.githubusercontent.com/74244333/118332513-80cab200-b50a-11eb-8b2c-f1db242ace25.png)

![bug](https://user-images.githubusercontent.com/74244333/118332431-5a0c7b80-b50a-11eb-8f87-7fdf1c5e57f7.png)

**Comment by piaoff** [comment]
@lazystudent3 yes, for the dragonic bee to mutate and get the allthemodium bee it needs the '' flower '' of its species and in beepedia it does not have the flower (nor in the JEI)

**Comment by Fynxes** [comment]
I have the following problem, the bees are displayed in JEI, but when clicking with left or right no further information is displayed for breeding, or flowers, or other information about the bees. 

The modpack runs on version 1.6.3c, but the error already exists since version 1.5.8 (which we had installed before).

Furthermore, since the version 1.6.3c is now so that the Beepedia leads to a crash when opening and server and client crash.

How can this error be fixed?

**Comment by piaoff** [comment]
@Fynxes in version 1.6.3c I no longer had this problem

**Comment by Letziah** [comment]
@lazystudent3 I updated to 1.6.3c and wither honeycombs are now fixed. But the dragonic bee still lacks its "flower"

**Comment by piaoff** [comment]
@Letziah yes

**Comment by lazystudent3** [comment]
@Letziah  I changed this in config and it works for me

**Comment by piaoff** [comment]
@lazystudent3 what did you put as a flower?

**Comment by lazystudent3** [comment]
@piaoff  I had old backup file so I just tried old flower for dragonic bee which used to be Dragon Egg. In version 1.6.3c flower for dragonic bee in config is set as Ender Crystal, so you can try it and see if it will work for you. In my case only changing flower back to Dragon Egg helped ( vanilla dragon egg )

**Comment by starfall18** [comment]
I checked the dragonic.json file, and the flower is set to End_crystal... the bees cant seem to harvest that... i tried it in both overworld and in the end, in and outside of an apiary... they just fly around like headless chickens and some try to hug me... i feel like they are trying to comfort me or something... (the bee: good job boy, at least you tried)
Maybe change the flower to something that isnt bouncing up and down and isnt on fire? Maybe idk... a simple end block... its already hard enough to get the bee... i dont know... can chorus fruits be placed down? or you could just make a recipie for a stationary placeable end crystal (like end crystal + obsidian block) that doesnt dance around and the bees could then hover over it and pollinate it without issues... or is the problem just that the coding for the bees to work on the crystals is not working?
Im not sure if my previous post was seen due to some issues, so im just posting this again...

**Comment by Fynxes** [comment]
> @Fynxes in version 1.6.3c I no longer had this problem
@piaoff 
So I can only say that I still have the problem in version 1.6.3c.

Both the problem with the crash when using the Beepedias, as well as the display problem with the bees, what can I do?

**Comment by whatthedrunk** [comment]
Works fine in the new version. thanks!
