### ISSUE TITLE
Weird Hydra spawns in the nether

### ISSUE THREAD

**Issue by xSwaight** [AllTheMods/ATM-6#1682]
Without changing anything in the configs, I have a lot of hydras spawned in the nether, so that my FPS drops below 10 and after a short time even the server crashes, as soon as I am in survival mode in the near. Here is a small video how the whole thing looks like in my case: 

https://streamable.com/36arkp

I play on the latest version. 1.6.4

**Comment by Dynorg** [comment]
I have the same problem. The portal was created in the Nether in High Hills and if you dig your way through the mountains then it lies in the server at home crashes. In game mode 3 you can go over the bedrock and there are tons of hydras like in the video above. The next biome is then Warped Forest and from then on the Nether becomes corrupt, that means you can neither get into the game via server nor single play unless you delete DIM-1. The problem is then that the portal is back to the Hydras and can't do anything.

**Comment by thevortex** [comment]
dupe #1656 see #1658

**Comment by Lynxboss-arch** [comment]
Im still having issues with the hydra spawn even after entering the code. Is there something else i need to do like reset the server?
