### ISSUE TITLE
Ghost Swarm in Soul Sand Valley

### ISSUE THREAD

**Issue by greyhatter** [AllTheMods/ATM-6#1686]
![2021-05-23_17 08 10](https://user-images.githubusercontent.com/77018090/119280772-6b374580-bbf8-11eb-8c73-1f104767cf1c.png)

Set down my nether portal and was unlucky enough to spawn into a soul sand valley. Got immediately ganked by dozens of 1500 health ghosts from Ice and Fire. Creative mode shows that it's just this biome, but I've yet to find any config changes that stop them from spawning by the dozen and haven't found anything in the mod that makes fighting that many possible + shouldn't be needed to progress into the nether.

**Comment by thevortex** [comment]
#1656 duplicate, resolve using #1658 and a reset of the nether this is a bug that came about due to a config change that we overlooked, as you can see from your minimap the biome you are in is not a normal nether biome, its from another dimension that BYG accidentally added because our blacklist got moved to a different file. download the config in the 1658 and put it in your config/byg/ folder, reset the nether and you should be good to go
