### ISSUE TITLE
Resourceful bees: Unable to breed Uranium and Uraninite bee with Slimy/Ender and Beeper.

### ISSUE THREAD

**Issue by pahb18** [AllTheMods/ATM-6#1758]
**Describe the bug**
Using ATM6 1.6.7. I can't breed the Uranium and the Uraninite bee. I'm following the recipe from JEI and verified it was the same recipe showing in the Beepedia. I'm putting everything needed into the breeder and it just doesn't do anything. I've tried other breeding recipes, and they seem to work as intended.

**To Reproduce**
For the **Uranium bee**, try to breed it in the breeder by using the recipe in JEI/Beepedia :
- An Ender bee with 5 nebulous heart
- A Beeper with 5 catalyzing gland

For the **Uraninite bee** :
- A Slimy bee with 5 slime pearl
- A Beeper with 5 catalyzing gland

**Screenshots**
![Breeder_Uraninite](https://user-images.githubusercontent.com/52642458/120906201-742b0c80-c625-11eb-8454-ec71fbddd714.png)
![Breeder_Uranium](https://user-images.githubusercontent.com/52642458/120906217-8c029080-c625-11eb-8569-d8785274ca96.png)
![Breepedia_Uraninite](https://user-images.githubusercontent.com/52642458/120906220-902eae00-c625-11eb-817c-af4e639e1b38.png)
![Breepedia_Uranium](https://user-images.githubusercontent.com/52642458/120906221-92910800-c625-11eb-8651-64425a327630.png)
![JEI_Uraninite](https://user-images.githubusercontent.com/52642458/120906222-94f36200-c625-11eb-98a4-d11e6581931f.png)
![JEI_Uranium](https://user-images.githubusercontent.com/52642458/120906224-96248f00-c625-11eb-83ec-662edece3102.png)

**Logs**
I'm not sure what logs I would need to attach. Please let me know if you need any.

**Comment by ladylexxie** [comment]
The bug is caused by a bee mismatch with the Beeper Bee. For some reason Creeper Bee is different from Beeper Bee.
To fix this, you need to basically release all the ones that say Creeper
![image](https://user-images.githubusercontent.com/30494658/121143986-7ebbf080-c835-11eb-9149-d07cc9c3b8ae.png)
and you need to catch new ones that say Beeper
![image](https://user-images.githubusercontent.com/30494658/121144015-867b9500-c835-11eb-8cf9-5a5dab18507a.png)
