### ISSUE TITLE
Sometimes sleeping in a bed will not pass night.

### ISSUE THREAD

**Issue by strangewolven** [AllTheMods/ATM-6#1784]
Sometimes when I get on my multi player server I go lay in bed and I will just lay there and it will not pass night it typically works when 1 person sleeps and it is usually just 1 person with the issue at a given time. I've tried changing beds and even used a sleeping bag and I just don't know what's happening.

**Comment by enitiaty** [comment]
so what you're saying is, when multiple people are online, if one person sleeps it doesn't pass the night?

**Comment by strangewolven** [comment]
I mean like I was effected and couldn't pass the night but someone else
could sleep and it would work just fine.  But it's not always the case It
happenes occasionally and it's not always just me sometimes it would happen
to my friends

Brooklin Page Ramagos

**Comment by DAmNRelentless** [comment]
I am not able to reproduce this and we haven't had any reports like that.
Did you modify the pack in any way?

**Comment by strangewolven** [comment]
We added a few mods but none of them should have effected sleeping we added
goblin traders, inventory pets and the undergarden is that ok?

Brooklin Page Ramagos

**Comment by DAmNRelentless** [comment]
I can't tell you. We can't give support for modified packs. It's at your own risk and your own responsibility then, sorry.
Otherwise we would have to install the same mods every time someone reports an issue to use to test stuff and with the amount of players we have, that simply is not possible.

Try to replicate the issue with the newest version of the pack without modifying it and open a new issue if it still persists.

**Comment by strangewolven** [comment]
That's ok then I was just curious thanks of looking into it for me

Brooklin Page Ramagos
