### ISSUE TITLE
Induction Smelter is unable to melt iron dust into an iron ingot.

### ISSUE THREAD

**Issue by clgarciab** [AllTheMods/ATM-6#1819]
ATM 6 VERSION 1.6.10
**Describe the bug**
When trying to craft Iron ingots from iron dust using the induction smelter, it doesnt work. Other minerals' dust do.

**To Reproduce**
1. Go to Induction Smelter.
2. Put some iron dust into the induction smelter.
3. Nothing happens.

**Screenshots**
![2021-06-15_13-21](https://user-images.githubusercontent.com/49439085/122044276-9a4a6c80-cddc-11eb-9eb0-497fb741c2ca.png)

**Comment by DAmNRelentless** [comment]
This is intended because it would cause recipe overlaps with this one:
![](https://i.imgur.com/kQ1QBow.png)

If you wanted to make that recipe, it would just smelt the Iron Dust instead of alloying the ingredients.
Tbh, smelting stuff is also not the purpose of an Induction Furnace. Use the Redstone Furnace for stuff like this.
