### ISSUE TITLE
Botany Pots Extremely low production rate

### ISSUE THREAD

**Issue by BushTrocity** [AllTheMods/ATM-6#1838]
Modpack Version 1.6.10

Botany Pots Rarely make anything now. I saw in the config that log have a 0.5% chance to be made in a botany pot. That can not be right.

**Comment by DAmNRelentless** [comment]
I don't know what "config" you are referring to.
The values have always been like that and not only since the last update.
This is an overworld modpack. It's not like Sky where you rely on something like Botany Pots to gain your resources.

You can simply farm in the overworld. The Botany Pots are just a cheap way to get some stuff automated very early so this ratio is justified.

**Comment by BushTrocity** [comment]
Ah Yes the cheap hopping botany pots that require terrasteel.

**Comment by DAmNRelentless** [comment]
> Ah Yes the cheap hopping botany pots that require terrasteel.

If you are not happy with our decisions, feel free to play another pack. I gave you an explanation, that should be enough.

**Comment by ladylexxie** [comment]
"Yes the cheap hopping botany pots that require terrasteel." 
Yes. If you've ever played through Botania, you'd know you can get Terrasteel in like 5-10 mins. What's there to complain about? It's not like you need x9 compressed stacks of Alfsteel.
