### ISSUE TITLE
Server Crash when near/in render distance to a certain players/worlds base/items/blocks/entities

### ISSUE THREAD

**Issue by joesitsolutions** [AllTheMods/ATM-6#1852]
We (The owner and I) don't have much clue what's causing the issue to be honest. I'll drop the crash log in here if anyone knows anything. The server runs fine normally with the following java arguments:
java -server -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=6 -XX:+AggressiveOpts -Xms8G -Xmx8G -jar serverstarter-2.0.1.jar
When I/anyone attempt to go near/to a specific location on the server it starts running behind and eventually crashes. We are on the latest 1.6.10 update of ATM6. In that location, there are refined storage systems, tinkers things, an automated mob grinder, magic stuff/circles from the mahou tsukai mod (Idk man whatever this player placed or used). It's repeatable every time anyone comes remotely near the base/location. The server crashes and rolls back automatically and it's fine after.

[crash-2021-06-17_22.14.23-server (1).txt](https://github.com/AllTheMods/ATM-6/files/6674875/crash-2021-06-17_22.14.23-server.1.txt)

We'll try some tshoot later on today/tonight and I'll update this issue thread as we go.

**Comment by DAmNRelentless** [comment]
It's not really a crash. It's the server watchdog intentionally shutting down the server because it can't keep up.
It's really normal for modded servers to run behind because there is a ton of stuff going on in the world especially in crowded areas with a lot of machines placed.
The only workaround for that is increasing the server watchdog time before it shuts down the server and to do regular restarts like every 3 hours.

Other than that, you could also profile which is causing so much lag in the area and fix it or remove it. You can use spark for that which is included in the pack.
That's nothing we can fix on our end and it's not really a pack thing.
