### ISSUE TITLE
Extra Storage/Extra Disks Recipes conflicting ATM 6 1.6.10 current

### ISSUE THREAD

**Issue by hyflicker** [AllTheMods/ATM-6#1858]
**All The Mod 6 Version - Current 1.6.10**

Extra Storage recipes showing up for 4096k Storage Part which is pointless since it only goes up to 16384k Storage Part. This recipe does not show up in JEI search but does show up when you right click the 1024K Storage Part from Extra Disks. Is there a point to have both of these mods in a pack since they accomplish roughly the same ends? 

Possible Solution A:
Remove Extra Storage from the pack.

Possible Solution B: 
Add in a recipe that lets you use the 16384K Storage Part from Extra Storage to craft the 65536k Storage Part for Extra Disks

**Comment by DAmNRelentless** [comment]
We can't just remove a mod, this will screw up peoples worlds.
I am working on a unification for those.

**Comment by pahb18** [comment]
This issue is kinda still present. I'm on 1.6.11, but also tested this on 1.6.12 and although the correct recipe shows up in JEI, when adding it to the pattern terminal of Refined Storage, the Storage Part is from Extra Storage instead of Extra Disks. It appears to work correctly with AE2 however.

Creating the pattern as is in RS, the recipe won't work when asking RS to craft the disk, however if you change the Storage Part from ES to ED, the pattern works correctly.

**JEI**
![ExtraDiskRecipe](https://user-images.githubusercontent.com/52642458/123552191-01ecaa00-d743-11eb-8464-3067457b953d.png)

**Adding it to RS pattern terminal**
![ExtraStorageInPattern](https://user-images.githubusercontent.com/52642458/123552194-09ac4e80-d743-11eb-8dc4-51374db41cc9.png)

**Adding it to AE2 pattern terminal**
![ExtraDiskInPatternAE2](https://user-images.githubusercontent.com/52642458/123552200-129d2000-d743-11eb-816f-bd7e5c2d7677.png)
