### ISSUE TITLE
[1.6.14] Mobs can spawn with indestructible armour.

### ISSUE THREAD

**Issue by cdgamedev** [AllTheMods/ATM-6#1991]
Not a bug, more of an OP feature that I don't know if it's intended.

I have a mob farm set up for endermen. Occasionally, they will spawn with armour which then makes its way into my RS system. I've started to get rid of this armour and use a disenchanter and salvager.

The Eternal Stella is meant to be "expensive" by requiring Vibranium and Allthemodium. But with this, I'm just getting armour at such a pace that the Eternal Stella isn't even worth making anymore.

Might be worth looking at?

https://imgur.com/a/JeC0AX4

**Comment by BovineShaman** [comment]
There are some things such as potion charms that require the Eternal Stella to become indestructible, because it cannot use the book, so it is still worth getting for some items.
Fishing can also get you tons of enchants like that as well, and that can be automated and produce probably a similar amount.
