### ISSUE TITLE
My server is crashing

### ISSUE THREAD

**Issue by energistix** [AllTheMods/ATM-6#1995]
Pack version: ATM6 1.

my server is just crashing whenever I start it

well the server just crashes when it starts and I don't know why or how

here is the crash report :
https://pastebin.com/jTVcm9PW

**Comment by radiomike** [comment]
It's a server watchdog error, which means that something is making a tick take too long. In this case, it looks like a lot of autocrafting by an rs system is the cause.
You can try increasing the timeout for this, with `max-tick-time` in your `server.properties`. Try adding a zero, that will get you 10 minutes to resolve the cause, rather than just one.

**Comment by energistix** [comment]
> It's a server watchdog error, which means that something is making a tick take too long. In this case, it looks like a lot of autocrafting by an rs system is the cause.
> You can try increasing the timeout for this, with `max-tick-time` in your `server.properties`. Try adding a zero, that will get you 10 minutes to resolve the cause, rather than just one.

thanks :) that resolved the issue
