### ISSUE TITLE
Crash on RFT Dimension - ATM6 v1.6.14

### ISSUE THREAD

**Issue by willmb** [AllTheMods/ATM-6#2018]
ATM6 v1.6.14

Got 3 server crashes when entering dimension on RFT.

3 crash-reports:

https://pastebin.com/eHAKVJCq
https://pastebin.com/miYXMGpu
https://pastebin.com/wwHWAVvx

**Comment by radiomike** [comment]
It's a server watchdog error, which means something is making a tick take too long. 
It's not immediately obvious what the cause is from the crash reports, it could just be the taking time to generate the chunks for the dimension. It's probably not helped by the number of entities in your world, there's quite a few listed, including a bunch of items in one of the rftools dimensions.
Something that you can do, which will give you a bit more time to sort things out is increase the timeout for this. You can do it by changing `max-tick-time=60000` in your `server.properties` file. I'd suggest just adding a 0, that will give you a 10 minute timeout, which may be enough to let the dimension load or deal with the entities in your world.
