### ISSUE TITLE
i am trying to load in the game but i think i don't have a enough memory heap to load the game. which mod do you think is unneed in this mod pack. 

### ISSUE THREAD

**Issue by da7431** [AllTheMods/ATM-6#2089]
i am trying to load in the game but i think i don't have a enough memory heap to load the game. which mod do you think is unneeded in this mod pack. plus i want tog get alex mobs.
i think i need to get rid of 50 to 100 mods.
any suggest on what mod i don't need

**Comment by LilHaramBae** [comment]
If you have 8-16 GB of ram and have around 4-6 GB allocated to Minecraft, you should run the mod pack.

Mods-wise, keep the ones you want to play, personally, I suggest keeping **Mekanism** since that can help you out big time with automation and **Bigger Reactors** for power.

**Comment by dandud100** [comment]
Removing mods will cause trouble, just allocate 6 - 8 GB to Minecraft and you can play this modpack.

**Comment by BovineShaman** [comment]
I'm pretty sure the recommended ram is 8-10 GB

**Comment by VarvatosVex** [comment]
I would suggest first downloading Java 16 with OpenJ9, and enabling the ZGC garbage collector.

I've found that when using that I can play the pack with around 4GB allocated, and the ram usage while in game drops to around 1.5GB after a while of ZGC doing its thing (on a multiplayer server, no idea about single player performance due to MC launching its own internal server).

It might be worth at least trying, before you start stripping out a bunch of mods.

Mind you that OpenJ9 might cause some mods to have undefined behavior (crashes/errors) due to working differently than normal HotSpot Java, but from my own experimentation, using Java 16 instead of Java 11 seems to fix those incompatibilities.
