### ISSUE TITLE
FTB Chunks causes players to jitter when another player enters minimap range. 1.7.6

### ISSUE THREAD

**Issue by RaxtusPrime** [AllTheMods/ATM-6#2095]
ATM 6 - Version 1.7.6       (Problem first noticed in version 1.7.2)
**Describe the bug**
Whenever another player enters minimap range, (shows up on the minimap after being too far away and coming closer.), both players experience a short distance jitter.

1. Play on a multiplayer server
2. Have a player move in and out of minimap range
3. See error

**Additional context**
Playing on a hosted server with Bisect Hosting.
One player is using Minecolonies (not sure if related)

**Comment by Youngstin** [comment]
ATM Versions 1.7.6 and 1.7.7
The mod causing this issue seems to be the **Shrink mod for 1.16.5 version 1.1.5**

_The FTB Chunks mini map just shows the view distance range, so that is the range a player would come into view for you._

**Steps to reproduce the behavior:**
1. Have a multiplayer server with at least two players.
2. Have two players be out of view distance of one another and start moving closer to one another.
3. Once the players are in view the jitter will occur.

**Additional Context:**
Server was on 10 chunks view distance and 12GB of ram.
Server was privately hosted on player's PC.
Issue occurred for both 1.7.6 and 1.7.7 for us (did not try previous versions).
Once the players were in view of each other with this mod will cause a jitter for both players, but not others on the server at the same time.

**Comment by ladylexxie** [comment]
Cannot reproduce the problem, if it persists please report it [here](https://github.com/FTBTeam/FTB-Chunks/issues/new/choose).
