### ISSUE TITLE
Industrial Foregoing introduces server crashing bug with /tank/null docks

### ISSUE THREAD

**Issue by Reinitialized** [AllTheMods/ATM-6#2112]
More details over [on this issue](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/1145).

The intent of this issue to track the status of updating the modpack when IF pushes an official release containing the fix or if ATM6 is willing to use a custom build containing the fix. Either solution works, as a fix already exists and is confirmed working on a server I manage using a custom build of IF.

**Comment by Claudibunsen** [comment]
not sure if doing this correct, but.

for actuality's sake; the bug also seems to affecting use of mekanism blocks

steps to reproduce

*build dock, insert tank (nether star tank in my case)
*pipe in fluids from a mekanism fluid pipe (elite in my specific case)
* watch as server crashes
* retry after restart, and watch as on log-on/chunk loading; everything crashing again

**Comment by jebjordan** [comment]
That sounds like it's probably not due to the dock, since with a tank in it no problems should really be occurring. 
The problem this issue is about was IF not checking properly before doing stuff. (and the dock being empty)

But either way, you should probably open an issue on either of those githubs since that doesnt sound like the same problem.

**Comment by Claudibunsen** [comment]
ok, it seemed to me like a problem that was related to tanknull, and its.. for me unknown problem that causes it to pull the server down, and subsequently crashing as soon as the chunk is loaded in
