### ISSUE TITLE
Minecraft crashing after joining server (1.7.11)

### ISSUE THREAD

**Issue by AcelZeroX** [AllTheMods/ATM-6#2236]
1.7.11 Game and Server

**Describe the bug**
After updating my server from 1.7.2 to 1.7.11 my game crashes when i join my server.

**Logs**
Please use a paste site for logs, instead of putting the file directly in the issue, not only is this easier but also means we can view on mobile when we are not at our computers.
Here's a list of some paste sites and their size limits:
https://pastebin.com/prpeDK4j

**Comment by AlexHailstone** [comment]
I have been experiencing this as well.  I went from .8 to .11. 

I had a whole base setup and originally had thought this issue was due to too many things in one area, however I'm getting memory leaks on my server and it will take all the RAM I allocate and more.

I.e. I allocated 9.5 GB and upong startup, server is for 2 people,  it sits at 3.7GB/4.5 while both of us play.... after about 12+ hours I'm sitting at 10.2GB and pegged at 100% RAM usage on the server until I restart the server.

Something is causing a runaway in the modpack, as I had to start a new world because the other crashes right after a 'joining world.....' and won't ever fully load.

**Comment by ladylexxie** [comment]
This is an issue regarding Bigger Reactor, we get these a lot but we can't do anything about it.

**Comment by RogueLogix** [comment]
Correction, its is a FramedBlocks issue, that has been fixed in dev
https://github.com/XFactHD/FramedBlocks/issues/49

coremods on FramedBlocks' part make the stacktrace less than clear here

**Comment by ladylexxie** [comment]
People normally aren't dicks about it either.
