### ISSUE TITLE
Game Crashes at Launcher

### ISSUE THREAD

**Issue by CyclistBrad** [AllTheMods/ATM-6#231]
**Describe the bug**

Downloaded from Twitch at on 26 Oct 2020 

**To Reproduce**
1. Download ATM 6 from Twitch
2. Click Play
3. Click Play on Launcher
4. Wait
5. Crash
![ATM6 Crash](https://user-images.githubusercontent.com/63928100/97231377-5fda8380-17a9-11eb-8a19-49ad3a3b1569.PNG)

**Expected behavior**

Load screen

**Screenshots**

![ATM6 Crash](https://user-images.githubusercontent.com/63928100/97231377-5fda8380-17a9-11eb-8a19-49ad3a3b1569.PNG)

**Additional context**

**Comment by CyclistBrad** [comment]
I found this line in the log

[16:35:10] [main/FATAL]: Failed to find Minecraft resource version 1.16.3-20200911.084530 at C:\Users\Darth Revan\Twitch\Minecraft\Install\libraries\net\minecraftforge\forge\1.16.3-34.1.25\forge-1.16.3-34.1.25-client.jar

the net folder does not exist in that directory. I thought it might have been a bad install, uninstalled, reinstalled, same error.

**Comment by CyclistBrad** [comment]
[latest.log](https://github.com/AllTheMods/ATM-6/files/5441761/latest.log)

**Comment by thevortex** [comment]
in the twitch launcher, click the 3 bar menu icon in the top corner of the app, choose file - settings, select minecraft from the settings tab, and change your minecraft installation folder to somewhere on your hard drive in a folder that has no spaces in the name(twitch is having issues accessing your Twitch install folder because of the space in your windows username :( ) after choosing a new install path for Twitch(Maybe C:\Twitch or something similar) then reinstall the pack and let me know if it works for you( or you could use a mod pack manager/launcher like [GDLauncher](https://gdevs.io/) and not have to deal with Twitch's glitches

**Comment by SodaPortal** [comment]
I had the same issue until I disabled GSYNC for the java executable, I was running in fullscreen/windowed GSYNC on three 1440p monitors

**Comment by CyclistBrad** [comment]
Changed the directory as Vortex suggested and it worked! Thanks for the help, I would have never figured that one out on my own. Curse launcher never had these issues... I will have to look into that GDLauncher.
