### ISSUE TITLE
Server crash when joining world

### ISSUE THREAD

**Issue by Elimas4** [AllTheMods/ATM-6#2409]
When I join the world on my dedicated server, the server crashes when loading the world.

**To Reproduce**
1. Use modpack version 1.8.3
2. Use a dedicated server
3. Start the server
4. Join the world

**Additional context**
The only information it gives me when crashing is that Watchdog stopped the server because a tick took more than 60 seconds. I tried disabling it by putting -1 for the max-tick-time but now the server just freeze when I join it. Everything was working well yesterday and for some reason, when i tried connecting this morning it crashed.

**Logs**
https://pastebin.com/34GbEEWm
https://pastebin.com/LJJgVV7C

**Comment by radiomike** [comment]
The crash is being caused by the over 99000 items in your world. Rather than set `max-tick-time` to -1, your probably better off settingiit to 600000, which will give you 10 minutes to resolve the cause.
Use the command `cu entity remove byType minecraft:item force` to remove them. You should then look for the cause, likely to be either a mob farm or overflow from a pipe filling a full inventory.

Crash utilities has a useful gui to help you find the cause, if you're opped. Use `ctrl-u`

**Comment by Elimas4** [comment]
That’s strange since the only thing i changed before that happened was to put a botany pot with endgame seeds in it. I don’t understand how it could overflow since it stops when the inventory below it full. I’ll check that later tho. Thanks for the lead !

**Comment by radiomike** [comment]
It's unlikely the botany pot caused this, probably just a coincidence. The overflow is likely to have been happening for a while, it's just the build up of items causing the long ticks. Depending on your system, it may be able to cope with 40/50000 items, but not 99000.
