### ISSUE TITLE
Minecraft crashing after open world, Update from 1.6.14 to 1.8.3 

### ISSUE THREAD

**Issue by GabrielDZN** [AllTheMods/ATM-6#2432]
minecraft crashing after open world
Version 1.8.3

1 open minecraft
2 open the world
3 wait
4 crash

Additional Contexts

A few days ago I made a post reporting the same bug, and I was told to use a nbt editor to remove items from my inventory as it was causing the crashes, but I did 3 tests, I erased my inventory using nbt editor in Level.dat and nothing happened (I also deleted the playersdata from the map folder)

my last post:https://github.com/AllTheMods/ATM-6/issues/2412

2 I tried to open the map on another computer with another Username and same bug

3 tried to open the map in older versions, but didn't get much, other than 8 atm versions consuming space xD

I'll be leaving crashreport, and my save in case you want to take a deep look at my level.dat (of course the map without any level.dat changes)

https://www.mediafire.com/file/drr3h24n58yxtrc/Gabrilandia+The+End!.rar/file
https://www.mediafire.com/file/drr3h24n58yxtrc/Gabrilandia+The+End!.rar/file
https://www.mediafire.com/file/drr3h24n58yxtrc/Gabrilandia+The+End!.rar/file

https://pastebin.com/mHwTUYkJ
https://pastebin.com/mHwTUYkJ
https://pastebin.com/mHwTUYkJ

**Comment by ladylexxie** [comment]
You can't expect to update from 1.6 to 1.8 and play in the same world.

**Comment by GabrielDZN** [comment]
> You can't expect to update from 1.6 to 1.8 and play in the same world.

why not, you mean i take everything i've done on my map and throw it away?, wtf that should be bullshit. from what I've read, the errors have to do with applieds, are you sure it's a problem with inventory?, imagine you have a giant map and lose it just because of a modpack update, none of the changelog says you have to create a new one map, they just recommend, ....

**Comment by tanyan-tanyan** [comment]
There's nothing wrong with what the above developer said and they don't deserve that kind of response from you considering your bad practice of taking care of your save. Large modpacks are extremely volatile and skipping versions when updating is something you should NEVER do on world saves.

When they recommend a new world, it's because they know that a mod they added could cause issues in worlds when upgrading the modpack (there was a warning like that for the changelog of 1.18). 
As well as that, you should approach updating your world responsibly - always take backups and update to the next version step by step, rather than skipping 20+ versions in one go. Nobody will realistically be able to figure out what is different about a modpack from 20 versions ago and why an update is causing problems like this.

As for the actual log: A developer friend I spoke to says it might be to do with inventory but not player inventory, something about AE2 crafting. It might also be a mod that created a broken itemstack and threw it to AE2.

The above does not really narrow anything down, so do you now understand why it's pointless to take on this issue?

**Comment by ladylexxie** [comment]
Oh jeez, I don't know.. if only _someone_ would've said that we expect people to make new worlds...
![image](https://user-images.githubusercontent.com/30494658/134577935-ae3e4fb3-74f2-41b4-87fe-3ebfa9b07bcb.png)
Couldn't be me writing that...

**Comment by Floppa-8765** [comment]
> Oh jeez, I don't know.. if only _someone_ would've said that we expect people to make new worlds...
> ![image](https://user-images.githubusercontent.com/30494658/134577935-ae3e4fb3-74f2-41b4-87fe-3ebfa9b07bcb.png)
> Couldn't be me writing that...

no ofc not why would anyone make a new world ITS NOT LIKE IT TELLS YOU TO ANYWHERE
