### ISSUE TITLE
Unable to access nether

### ISSUE THREAD

**Issue by RobertCoulter95** [AllTheMods/ATM-6#246]
Hello. Was able to access the nether from multiple portals. Not sure what caused the issue but no one is able to enter the nether.
Tried:
1. Restart the world
2. Delete the nether for the world
3. Make a new portal
4. Making player OP
None of them worked. 
This world was not updated from a previous version, it was always ATM 6 1.16.3

**Comment by GrokDuckFarmer** [comment]
Getting the exact same issue on my server.  Nobody is able to get to the Nether or End using the portals or waystones bound there.

It was working with 1.1.8 but is no longer working after upgrading to 1.1.9b.

**Comment by rzx3092** [comment]
I can confirm. Both nether and end appear to be broken on server for 1.1.9b

**Comment by rzx3092** [comment]
OP:
Main page states 
"Such as [FULL][1.37] My game is broken! Also include any added mods you may have put in, into the description of the issue."

You may need to edit the title

**Comment by NudeShrimp** [comment]
I just updated to 1.2.0 and it still seems to be broken

**Comment by Rader2146** [comment]
Same issue on 1.2.1.

Cant access the Nether or The End via portals or waystones.  the nether and end arent even options in the /execute in [dim] command.

**Comment by HackedGibson** [comment]
Using "NBT Explorer" I noticed in the 'level.dat' file after the 1.2.1 update (updated from 1.1.6) under dimensions "the_nether" and "the_end" are missing as well as the AE2 spatial dimension. I assume this why they are not accessible, in any way, since they don't exist. I have not figured out why they were removed, just that they were.

I managed to regain access to these dimensions by manually editing my 'level.dat' using "NBT Explorer" and adding the entries under the tag "dimensions" back in by copying and pasting the entries from the backup 'level.dat' I made before upgrading. As far as I can tell the dimensions are intact and still as they were prior to the disappearance post upgrade.

<img width="1398" alt="level-dat" src="https://user-images.githubusercontent.com/74121301/98454792-47327c00-2160-11eb-8f41-d1e7247ebcc8.png">
