### ISSUE TITLE
Resource screen crashes modpack?

### ISSUE THREAD

**Issue by DeadEyeSavage** [AllTheMods/ATM-6#269]
So I just downloaded the modpack last night thru twitch.
 I crash every time I hit done on the resource pack screen. With or without me adding a resource pack. So just to be sure I deleted the entire pack manually then had twitch redownload it. It loads straight from twitch no problem but if:

1. Go to options
2. Click Resource Packs (i do nothing on this screen and there is no additional files I have added)
3. Click Done
4. starts to load but will crash eventually.

So if I launch the pack then go straight into single player it works for a time but any traveling will cause a overlay crash.

I never seen so many things in the resource screen on any mod pack before so I assume the issue is in there. Hopefully this helps? As i see the pack was just updated yesterday. I am trying to revert to previous version to see if it works.

**Comment by Heli0saurus** [comment]
I believe I ran into the same issue, here is the [Pastebin.](https://pastebin.com/UibZuU48) Resource pack worked without a hitch on prior releases.

**Comment by NetMasterFlex** [comment]
I have experienced the same issue.  The problem I was having was attempting to apply Soartex Fanver 8.02 or 7.03 as a resource pack.  1.  pre-placed either resourcepack "Soartex_Fanver_(8.0.2).zip" or "Soartex_Fanver_7.0.3.zip" and even "Clarity-1.16.zip" in the Resourcepack folder and attempt loading the game.  

The game loads fine to the game menu.  When when I click Options > Resource Packs, then select any of those packs, click the play button to move the pack to the right side, then DONE.  The Mojang Title screen comes pack and the progress bar loads.  Eventually the game crashes.

Finally, by mistake, I loaded the game to the main menu, opened the Resource Pack folder via Options > Resource Packs and just the simple act of me visiting that page in the menu then clicking DONE, the Mojang title screen appeared with loading bar, then after about 3-4 minutes crashed.

The attached crash report was from just visiting the Resource Pack page and clicking DONE.  Similar to what DeadEyeSavage is reporting.

This issue started happening for me in version 1.2.0.

Version 1.19.b I had no issues adding Soartex Fanver 7.03 resource pack.  The resource packs can be downloaded from Curseforge Based on DeadEyeSavage, this issue is not related to attempting to apply a resource pack, but does happen as a consequence of navigating to the Resource Pack menu and clicking Done.

[crash-2020-11-04_14.22.45-client.txt](https://github.com/AllTheMods/ATM-6/files/5490842/crash-2020-11-04_14.22.45-client.txt)

NMF

**Comment by iAbuser** [comment]
> I believe I ran into the same issue, here is the [Pastebin.](https://pastebin.com/UibZuU48) Resource pack worked without a hitch on prior releases. EDIT I should also add it crashes immediately after Atlas Stitching, then the screen goes blank and then a CTD

This is been an issue for the last couple updates. Possibly immersive engineering or something that’s conflicting with it.

**Comment by NetMasterFlex** [comment]
@iAbuser I'm currently running a local server and have a few people connecting to it on my LAN.  I will try a client side test by removing IE, applying texture and running single player.  If successful, we might be able to conclude that there is some sort of conflict with IE as you stated in your comment.

**Comment by iAbuser** [comment]
> @iAbuser I'm currently running a local server and have a few people connecting to it on my LAN. I will try a client side test by removing IE, applying texture and running single player. If successful, we might be able to conclude that there is some sort of conflict with IE as you stated in your comment.

Any news?

Thanks

**Comment by NetMasterFlex** [comment]
UPDATE! I removed Immersive Engineering Modpack, Loaded the game, applied resource pack to the game via the GUI Resource Pack selection page, clicked DONE.  

It took about 10-15 minutes to return back to the Options menu.  The overlay of the menu reflected that Soartex Fanver 8.0.2 texture pack was applied successfully.
Single Player world loaded although that took a good 5 minutes as well, but did load successfully.
There is something about Immersive Engineering that is conflicting with the Resource Pack.  Just don't know what it is.

I just re-added Immersive Engineering back to the Mods folder.  I'm currently waiting to see if the game will load now that I was able to move the resource pack from the left over to the right successfully.  Will post again shortly.

**Comment by NetMasterFlex** [comment]
UPDATE2! After re-adding Immersive Engineering back into the Mods folder, the Soartex Fanver 8.0.2 resource pack was back on the left hand side on the Resource Pack selection screen and NO LONGER applied to the game.

I'm concluding that there is some sort of conflict with Immersive Engineering Modpack and applying resource packs, or even viewing the resource pack menu, clicking DONE.

I hope the modpack devs can determine root cause because it sucks not being able to use a resource pack.  

Note: Optifine installs and works no problem as well.

**Comment by NetMasterFlex** [comment]
I'm report this as a Bug.  IE is causing the game to crash when the Resource Pack Menu is visited or when any attempt is made to add a modpack to the game.  Please resolve as soon as you are able.  Modpack ATM6 Version 1.2.1 and 1.2.0.

**Comment by NetMasterFlex** [comment]
SOLVED!!  This message is for the Modpack devs.  Please update Immersive Engineering from Version ImmersiveEngineering-1.16.3-4.1.1-124.jar and replace with ImmersiveEngineering-1.16.3-4.1.1-127.jar

After performing this action on my client, my client doesn't crash after visiting the Resource Packs menu, nor does it crash after I moved Soartex Fanver 8.0.2 from the left side (Uninstalled) to the right (Installed), then clicked DONE.

The load time to apply the pack took a good 10 minutes, but the client didn't crash and I am able to play the game with the resource pack applied.

NMF
