### ISSUE TITLE
[Crash]: Server will not start

### ISSUE THREAD

**Issue by bobothehobo2** [AllTheMods/ATM-6#2875]
### Possible Fixes

Yes

### Modpack Version

1.8.17

### What happened?

I had to remove the AdditionalEnchantedMinerMod to get the server to start.  Thanks!

### Crash Log

https://gist.github.com/bobothehobo2/9b47df36fd5724895ce4cd4e6a8c8a2c

**Comment by radiomike** [comment]
Actually, looks like you are missing some mods, probably due to issues downloading from curse.

https://www.curseforge.com/minecraft/mc-mods/scalable-cats-force/files/3297906 
and
https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib/files/3413938

There may be others. You should have 336 mods in your mod foldder.

**Comment by bobothehobo2** [comment]
Yeah I manually added those and got different errors.  I rolled back to .16 no biggie.  Thx!!
