### ISSUE TITLE
[Crash]: java.lang.Error: ServerHangWatchdog detected that a single server tick took 120.00 seconds

### ISSUE THREAD

**Issue by tankirules** [AllTheMods/ATM-6#2957]
### Possible Fixes

Yes

### Modpack Version

1.8.19

### What happened?

My server crashed because apparently  tick took too long, I want to find out why.

### Crash Log

https://gist.github.com/tankirules/74391b40c35601536ec7eef98f945da8

**Comment by radiomike** [comment]
Looks like it's being caused by a slime entity that is stuck somewhere. You can use crash utilities to find it - `ctrl-g` in game or `cu entity find minecraft:slime`from console. It's also possible that it's a tinkers slime, so you can just swap out the entity id there. You can also use the observable mod or `forge track start entity 10` followed by `forge track entiy` to see if that's the bad entity.
 Use `cu entity remove byType minecraft:slime force` to remove all slimes.

**Comment by tankirules** [comment]
> Looks like it's being caused by a slime entity that is stuck somewhere. You can use crash utilities to find it - `ctrl-g` in game or `cu entity find minecraft:slime`from console. It's also possible that it's a tinkers slime, so you can just swap out the entity id there. You can also use the observable mod or `forge track start entity 10` followed by `forge track entiy` to see if that's the bad entity. Use `cu entity remove byType minecraft:slime force` to remove all slimes.

Unfortunately I do not know when this happens, I just randomly try to connect to the server and then it crashes :/
