### ISSUE TITLE
[Crash]: Refined Storage? - ServerHangWatchdog detected that a single server tick took 60.12 seconds (should be max 0.05)

### ISSUE THREAD

**Issue by SpikePls** [AllTheMods/ATM-6#3018]
### Possible Fixes

Yes

### Modpack Version

1.8.21

### What happened?

Refined storage appears to have problems with the update or mods.
Cannot start the server. It breaks immediately.

Running a 10GB-RAM server (provider = g-portal), nothing special. Tried their region fixer. Didn't work.
Backups work finely, but eventually we run into this problem again.

Crash report mentions refined storage a lot. especially the "ExternalStorageNetworkNode". They are connected to the Drawers from the drawer mod. 

Please help. Maybe you know a fix. Thanks for listening.

### Crash Log

https://gist.github.com/SpikePls/394d50fda32e6e453a80954a83be1b42

**Comment by radiomike** [comment]
It's a server watchdog error, which means that something is making a tick take too long. In this case it does look like it's to do with a refined storage "external storage" updating when the drawer, or whatever it's connected to is updating - possibly due to large amounts of nbt on the stored items. 
To get the server running again, try increasing `max-tick-time` in the `server.properties` - try adding a 0 to make it a 10 mins timeout, or if that still fails try `-1` to disable it. That should allow the server to start and give you some time to find the particular cause. You might find the `observable` mod useful for this - it's included in the pack.
