### ISSUE TITLE
[Crash]: when world are open

### ISSUE THREAD

**Issue by zSalocin** [AllTheMods/ATM-6#3056]
### Possible Fixes

No

### Modpack Version

1.8.23

### What happened?

I use MultiMC lauch but i cant loaded my world, pls help

### Crash Log

https://gist.github.com/zSalocin/e496667aa2725639c5ce9de9253c0c39

**Comment by jeremiahwinsley** [comment]
Looks like you have corrupted configs, this can be caused by crashes or by 3rd party antivirus programs. The one mentioned in the crash log is `rangedpumps-server.toml` which can be found in `saves/<save name>/serverconfig`. You can just delete or rename the whole serverconfig folder and let it regenerate from defaults, as there are likely to be a few more corrupted configs.

**Comment by zSalocin** [comment]
Thx @jeremiahwinsley
