### ISSUE TITLE
Obvious WitherProof Block

### ISSUE THREAD

**Issue by Haloribald** [AllTheMods/ATM-6#309]
**Is your feature request related to a problem? Please describe.**
Can not find any Block in JEI with "#wither", "#witherproof" etc. that a wither would not be able to destroy.

Since a lot of recipes require Nether Stars it would be nice to have such a block in the pack since mystical agriculture and resourcefull bees require a lot of nether stars to even set up.

**Describe the solution you'd like**
make a block witherproof (e.g. compressed obsidian) and add a description, so it is easy to find in JEI

**Describe alternatives you've considered**
Wait for rftools to add the block protector to 1.16.3

**Comment by DeathOfTime** [comment]
i think it is cyclic that has something. though there are likely other blocks. it is eight pieces of black glass. shaped like a upside down chest plate. with a piece of obsidian in the bottom center. if i remember right. I haven't fully tested it though. i tend to just fight him on my claim. Where all blocks are wither proof. Not that he lives long enough to truly find out otherwise

**Comment by WhitePhant0m** [comment]
search with `$wither` or `$witherproof`
$ is used for tags

**Comment by NeoSono1981** [comment]
unless the latest modpack update removed the shield projector from rf tools it is already in the game and working. the only thing that didn't work was the function to mimic a block. the shield is always invisible for me. also as mentioned above cyclic has tempered glass which is wither proof too.

**Comment by patrick96** [comment]
Searching for `#wither`, you will find Cyclic's tempered glass and just searching for `wither` will give you witherproof block and witherproof glass from mystical agriculture.

**Comment by Haloribald** [comment]
ah okay, dont know why i didnt find it before thanks :)
