### ISSUE TITLE
Salvager is configed to Trashcan

### ISSUE THREAD

**Issue by gogedo** [AllTheMods/ATM-6#349]
silentgear-common.toml
[salvager.partLossRate]

**current values are min = 0.9 ;  max = 1.0**
So you must have an item with 10 ingots and 100% Durability to get back 1 ingot.
Lower 10 ingot's (that are all items) it's trashcan !

	[salvager.partLossRate]
		min = 0.0 #full Durability all back
		max = 1.0 #low  Durability nothing back
 
50% Durability gives back half, 2 ingot from Helmet nothing from a shovel

 1% Durability and max = 0.8 rounds it up and you get 1 ingot back from Helmet (5 ingots)
and 50% gives back 3 ingots from Helmet
 
so i think
     min = 0.0
     max = 0.8
are good playable values

**Comment by ViRb3** [comment]
I can agree that the initial configuration is a bit absurd. I salvaged a ton of almost brand-new equipment and absolutely nothing came back.

**Comment by ViRb3** [comment]
@WhitePhant0m I noticed that you were the one who made this change in 5b24362c036bb8b381c11a85acfafd95e4cb7022. Any specific reason for that? Could we change it to, say, min 0.6 max 0.8, so it's a bit more usable?

**Comment by gogedo** [comment]
The announced changes are from min = 0.0 max = 0.9 to min 0.5 and max = 1.0
But in config it's min = 0.9 max 1.0 so that's wrong!
Test with min =0.5 max= 1.0 full Durability
get back
Shovel    = 1 Stick
Sword     = 2 ingot
Boots     = 2 ingot
Helmet    = 1 ingot
Pickaxe   = 1 ingot
Leggings  = 5 ingot
Chestplate= 2 ingot
seams there is a loot of random

**Comment by IGGYVIP** [comment]
:O so much gear gone before i spotted :( 
please fix to usable values

**Comment by ViRb3** [comment]
The Salvager was effectively disabled (turned to Trashcan) due to the bug described above by @gogedo. I have reported this issue to the mod author @ https://github.com/SilentChaos512/Silent-Gear/issues/262. Once it is fixed, we can re-visit this. In the meantime, I will disable Salvager crafting and leave an explanation in JEI, in hopes to avoid people losing their items.

**Comment by andrewsf** [comment]
More useless than a Salvager that returns 10% of ingredients is a trash slot, which is now how I will have to dispose of mob drops.

**Comment by IGGYVIP** [comment]
Yeah with server owner we had to manually change the file to 50-90% and yea it's random what you gonna get but it's better than bin option..

**Comment by andrewsf** [comment]
> The announced changes are from min = 0.0 max = 0.9 to min 0.5 and max = 1.0
> But in config it's min = 0.9 max 1.0 so that's wrong!

That's not a bug in the mod. That's a poor changelog note in ATM6.

**Comment by JustJinxed** [comment]
I'm not sure why this item was marked for disabling, that seems a bit extreme.  It's only been about 15 hours since the devteam replied back, so hopefully, you'll readjust the config? I've manually set it back on my own server to the intended value, frankly because there isn't a whole lot of items I can see being run through this. Most any unique items from a mods can't be, and I can go about tweaking anything that comes out abusive. With things like mystical ag in the pack, I'm not sure what the balancing intention here was to disable it in the first place? Or was it just because it seemed the look should have been static? Because if so, it makes me wonder what else was changed that you felt wasn't "as intended"? 

(please don't think I'm being negative- I totally understand the dilemma in making adjustments, I just really question the intent on this one, other than that old trope of "I hate item disassemblers / they ruin the game" we used to see go around all the time.)

**Comment by alexgurrola** [comment]
@JustJinxed I totally agree.  I enabled it on mine as well.

**Comment by thevortex** [comment]
disabled by configuration by default in the pack. feel free to change it on your own server if you like.
