### ISSUE TITLE
1.3.1 No Ice and fire Spawns

### ISSUE THREAD

**Issue by lilwilisjr** [AllTheMods/ATM-6#356]
Fresh install of 1.3.1 Server/Client and cannot get any ice and fire spawns in overworld or the other dim

**Comment by ViRb3** [comment]
Known issue, will be fixed with next update.

**Comment by willownezz** [comment]
can confirm **iceandfire-2.1.2-1.16.4** fix the spawning of creatures

**Comment by ViRb3** [comment]
ATM6 is configured to spawn in THE_OTHER dimension, but Ice and Fire 2.1.3 breaks spawning outside of overworld, so this still isn't fixed for now.

**Comment by JohnMartial** [comment]
Might be a dumb question, but me and a friend of mine is playing on the ATM6 1.3.0 Server/Client version and been looking for ages for these wonderful dragons. Good to know that we don't have a corrupt file or anything like that, but if this gets fixed in the future would there be issues in updating the server (moving the world file or something similar to not lose the progress and adventure we have had so far)?

**Comment by ViRb3** [comment]
You would not have to alter your world to get the dragons once a working update is released. All you would need is a regular update. Nothing should break.

**Comment by ViRb3** [comment]
Tracked here: https://github.com/Alex-the-666/Ice_and_Fire/issues/3160

**Comment by Pdiddy973** [comment]
should be resolved in pack version 1.3.9
