### ISSUE TITLE
Memory issues, maybe? or settings?

### ISSUE THREAD

**Issue by Zaniukmartin** [AllTheMods/ATM-6#365]
Hi, I'm new to modded minecraft
![1](https://user-images.githubusercontent.com/74916511/99976737-7f66cb00-2dac-11eb-85a6-65211a798b34.png)
 and recently started playing ATM6.
For some reason I can normally start a game but play it only for a short while after which I start to get some chuncks not loading and sometimes "waiting for server" when interacting with items (in single player world).
I'm running 16x AMD Ryzen 3700X
16 GB ram (8066 of w/ are allocated in launcher to minecraft)
RTX 2080 Super
I would assume the PC is fast enough for minecraft

Help?

**Comment by ViRb3** [comment]
This seems like a server problem. Where are you hosting? What JVM args are you using for the server? How overloaded is the server? Check my last response in #340 for profiling steps.

**Comment by Zaniukmartin** [comment]
@ViRb3 Its a single player local world. I'm not hosting anything.

**Comment by ViRb3** [comment]
Single player loads a full-blown server along your client. You may want to offload it to a dedicated server for better performance. Otherwise, check out these links for JVM argument tuning:
https://reddit.com/r/feedthebeast/comments/5jhuk9/modded_mc_and_memory_usage_a_history_with_a/
https://xealgaming.net/threads/optimising-your-minecraft-jvm-arguments.4758/
https://cubedhost.com/help/en/articles/1648388-how-do-i-allocate-more-memory-to-my-minecraft-launcher-client-side

**Comment by Pdiddy973** [comment]
1.3.9 helped with loading times, if you still have an issue feel free to ask in the discord as well.
