### ISSUE TITLE
Add another dimension using my old world file

### ISSUE THREAD

**Issue by RickyvdBerg** [AllTheMods/ATM-6#411]
Is it possible to use my 1.3.1 world as an extra dimension for my 1.3.2 world and if so how?. Somehow, Astral sorcery doesn't spawn in my 1.3.1 world and it does in a newly generated world. So I would like to generate a new world for the server and keep the old world as a separate dimension.

**Comment by glahera** [comment]
I think it is possible if you're willing to go through the trouble of making it with their terrain generation and its own dimension ID, then leave a Mekanism portal chunk-loaded in that dimension so that you can teleport to the new Overworld and make one with the same frequency.
Also, of course structures do not "spawn", they are "generated", which means they cannot override existing chunks. You can try by just finding Astral Sorcery temples outside generated chunks (the one you've seen on your maps), I think you would have better luck at doing that than doing what you're suggesting.
