### ISSUE TITLE
Updating Server From 1.3.1 to 1.3.3 And Experiencing Random Crashes

### ISSUE THREAD

**Issue by nathangelderbloom** [AllTheMods/ATM-6#512]
Not sure if it matters or not but I am using MultiMC launcher. Also, I am not sure if this is where I am supposed to be posting this but here goes nothing...

So I realized my server (1.3.1) is out of date, so I downloaded and ran the new server files in a new folder. Afterwards I updated my client so I could connect to the new server and I connected to it so that all of the files would be generated in the new folder with the updated server (1.3.3). 

Next I took the old world file from my outdated server and replaced the one that was generated with the updated one with the one I have been playing on for a while. I also drag and dropped my old server.properties file so I did not have to redo everything in there and replaced the one that is in the new server folder. 

So where the issue comes in is when I log into the world, it runs for a little bit fairly well, and it crashes the server. 
It seems to be an issue that is caused by the game loading in something specific that causes a server crash. The error that I get in the client is: Internal Exception: java.lang.StackOverflowError

If I remember correctly, I faintly remember one of those Myrmex traders from the Ice and Fire mod flying around in that area but I am not sure that if it is the cause for the crash. I'll try and see if I can throw in the latest.log file. After reloading and moving towards the last known location for the Myrmex mob I crashed again after moving a little bit closer so I am fairly certain that that is the issue... Might just have to open this world in 1.3.1 in single player and get rid of the mobs/blocks that are related to them? (My friend spawned these mobs in as a joke on another player, I am aware that the world generation for Ice and Fire is broken in 1.3.1)
[latest.log](https://github.com/AllTheMods/ATM-6/files/5649842/latest.log)

**Comment by samparker5** [comment]
This happening to me on single player as well. I can play totally fine for about a half hour or so and then it randomly crashes. I have no idea why.

**Comment by nathangelderbloom** [comment]
Currently my buddy is dealing with the problem in singleplayer in 1.3.1. Apparently he had made it so that the requirements for making a Myrmex nest (having two of the Royal Myrmex mobs mate so that it makes a Queen Myrmex I think) and apparently this had grown to a very large degree. Which is weird because I barely have those chunks loaded in at any time, even though it is somewhat close to the area that I am normally in. 

But still, he is going to clear out the nests and get rid of the blocks related to the Myrmex and we will see if that fixes the issue. Will keep updated.

**Comment by samparker5** [comment]
Yeah I literally just started the pack and I have no idea why it is doing this. I don't even have a house yet and haven't gotten into any mods so I have no idea what is causing mine. I hope it works out for you guys!

**Comment by nathangelderbloom** [comment]
Out of curiosity, what version are you running?

**Comment by samparker5** [comment]
I just downloaded it today so I am assuming the most recent one, is that how it works? I am not sure how to check.

**Comment by nathangelderbloom** [comment]
https://www.curseforge.com/minecraft/modpacks/all-the-mods-6/files/3124239
This is the most recent version. I am not sure which launcher you are using but 1.3.3 is the most recent version. If you are not up to date with the latest version then you could be in a version were the issues you are experiencing have been fixed in later versions.

**Comment by samparker5** [comment]
Yes, I am on 1.3.3. I wonder if I would have the same issues if I went to the last version.

**Comment by NetMasterFlex** [comment]
@nathangelderbloom 

Maybe try updating a different way.

Run a LAN Server of ATM 1.3.3 and have been upgrading since 1.1.29.  I run the server on a Windows machine and here is my upgrade process.  This has yet to fail me and does not include any workarounds, and fixes that have led me to this point.

Here is my process.

Pre-Upgrade Steps.

1. Download and unzip the latest server files ie. ATM6 v1.3.3
2.  Shut down server ie. X out of the DOS window that displays server status.
3. Create a backup folder in a separate directory.  I call mine ATM6_v1.x.x_Backup.
4. Perform a select all within your current server directory and copy/paste it into the folder you just created.
5. Open the folder that contains the latest server files. (Should be 3 or 4 files).
6. Select all, copy/paste these files into your current server directory (The one to updated).  Accept any warnings of overwiritng existing files.

Upgrade by starting server.

1.  Double click the ServerStart.bat file and watch the loading of the server.  You will be ready to connect with your client once you see the last message....usually "The server can't keep up...."  This has been accepted as normal for me and typically doesn't come back that I'm aware of.

Update your client by installing a new instance of ATM6 with the version that directly corresponds to your server.  Leave your old instance in case you need anything from the files there.

Finally launch Minecraft and re-add the server ie. Name and IP address, then connect.

I have had no issues using this method of updating.  Hopefully you will have similar success.

NMF

**Comment by samparker5** [comment]
Also, I am using Curse Forge sorry I forgot to include that.

**Comment by NetMasterFlex** [comment]
> Also, I am using Curse Forge sorry I forgot to include that.

I would shy away from Curse Forge launcher.  It's too new and not thoroughly vetted enough to be claimed as stable.

Use Mutil-MC or GD Launcher for best results with ATM6.

NMF

**Comment by nathangelderbloom** [comment]
Was not aware that you could update it that way, I would have figured that putting those files in would just have tried to run the server as normal. I just got the world file back from my buddy, so I will try that updating method if what he did does not work, or if I run into additional errors. I have a feeling that the issue might have persisted if it does happen to be the result of the Ice and Fire mod, but we will see. Again, I will keep you posted.

Also samparker5, I am not sure how to check the version of your ATM 6 as I have not used it before.

**Comment by samparker5** [comment]
@NetMasterFlex Thank you! I will try that as well.
@nathangelderbloom I am on 1.16.4v1.3.3

**Comment by NetMasterFlex** [comment]
It's also best practice to backup your server files (All of them) prior in case something goes wrong.  @nathangelderbloom I hope you have a copy of the files pre-upgrade to 1.3.3.  Meaning a copy of ATM6 v1.3.1.
NMF

**Comment by nathangelderbloom** [comment]
Yes, I have one copy that I have not touched since copying all the data, all is good here, thanks!

**Comment by samparker5** [comment]
I am trying MultiMC now I will let you know if that works! 

Thank yyou

**Comment by NetMasterFlex** [comment]
If that fails for some reason you could also try an incremental upgrade where you first start at 1.3.1 then update to 1.3.2, then to 1.3.2b, then 1.3.2c, then finally 1.3.3.  In order to do that would have to update your client each time and test after each update to make sure your world loads etc.  I don't know if ATM Full releases are accumulative or not.

Just made mention of the above because it was a part of the path I took.  from 1.2.1 to 1.3.3 there were some bumps in the road that came up with regard to the nether portal and end portals being broken, world gen biome leaks, etc. that required specific work arounds to fix.

If you want faster help I would consider joining ATM6 Discord channel.  They have a ATM6-Help and ATM6-General chat rooms where SME's and users discuss problems and solutions.

NMF

NMF

**Comment by nathangelderbloom** [comment]
Ok so, it does seem that my suspicions have been correct. There was an issue when it comes to Ice and Fire with the Myrmex, more than likely going between versions of the mod, if there are any between ATM 6 1.3.1 and 1.3.3. I am surprised that the way that I updated the server did not cause any issues besides not carrying over my waypoints and possibly more that I have not noticed as of yet. 

So, everything seems to have been fixed after nuking the Myrmex out of the ground, quite literally as well lol. I am able to go into the area of where the nest used to be without issues.
@NetMasterFlex thank you again for the info on how to update the server, I was not able to find any info on that subject anywhere, when I googled it. 

@samparker5 hopefully any info in this thread helps you with your issue, it could be something else entirely, and I would explore the issue more, and if you think it warrants another issue thread like this one, then I would highly suggest you create one. But, I would try some more troubleshooting to see if you can figure our the causes for your issue. You can also make yourself vocal on their discord like Net suggested so you can get better feedback.

**Comment by samparker5** [comment]
Okay, thank you! I will join their discord :)

**Comment by nathangelderbloom** [comment]
No problem, and good luck!
