### ISSUE TITLE
Mekanism Ore compatibility 

### ISSUE THREAD

**Issue by GalloranTbk** [AllTheMods/ATM-6#526]
Is there a file to be added to make "Alltheores" compatible to Mekanism?

**Comment by Nonsanity** [comment]
Mekanism machines can process ATM ores. What isn't compatible?

**Comment by NetMasterFlex** [comment]
From my experience they are compatible. I have been able to triple my ATM ores using Mekanism specifically ATM and Vibranium so far.

**Comment by GalloranTbk** [comment]
Perhaps one of the aspects of the file got corrupted for my mods. But I tried on several newly generated worlds and still run into compatibility issues. The ores refuse to insert into the processing slot, and in some cases obfuscate pipes that attempt to do so.

**Comment by GalloranTbk** [comment]
Clarification, ATM ores such as allthemodium, unobtanium, vibranium do work with mek. But ores such as lead, silver, uranium etc from the mod "alltheores" do not.

**Comment by thevortex** [comment]
an update is coming within the next few days to add the full 5x processing for all ore you mentioned @GalloranTbk

**Comment by vedalken254** [comment]
@thevortex has this been deployed in/prior to 1.3.9b or are we still expecting the update? I just noticed the clumps problem myself on 1.3.9b with a fresh install and saw this issue already created. Uranium is for sure still affected. It enriches fine, but purification chamber or higher breaks due to the crusher not accepting the clumps.

**Comment by thevortex** [comment]
update coming on friday, full 5x will be working 1.4.0
