### ISSUE TITLE
ae2 wont work on ubuntu 20.04

### ISSUE THREAD

**Issue by michaellarson1000** [AllTheMods/ATM-6#567]
im using ubuntu 20.04 and all the mods 6 wont load, when i try to launch i get an error saying that ae2 failed to load and it wont let me play, the only way i can fix this is to disable ae2 extras but then i cant join any servers, ive tried reinstalling it and trying it on different loaders but it wont work.

**Comment by fgoebel** [comment]
What java do you have installed?
I think we had the same problem with this pack and a wrong java version.

Maybe you try it with openjdk8 64bit again.

And I think it would be good to include a crash report in the futurue everytime you have some issue, because it just takes longer for you to get the solution if not ;-D

**Comment by thevortex** [comment]
this is definitely a java issue, ae2 extras needs java 8 specifically, java 11 etc will not work

**Comment by Cntrldfusion** [comment]
yeah, I had the same problem with java 14, didn't Oracle say that Java 8 is EOL after this year, shouldn't Minecraft be moving towards more current version of Java

**Comment by michaellarson1000** [comment]
I did try with Java 8, but I might have to reinstall it and try again

**Comment by Letoric** [comment]
Is this still an issue?
