### ISSUE TITLE
[1.3.4c] Bees not spawning

### ISSUE THREAD

**Issue by Namoku** [AllTheMods/ATM-6#581]
Mana bee is not spawning in the biomes, and the guardian bee doesn't have biomes to spawn.

1. Go to your world 
2. Good luck with searching the bees

I don't know if I don't have good RNG for the mana bee but it's not spawning in a lot of biomes I visited. Guardian bee doesn't have a biome in the biome list in the NEI info.

**Comment by SlyScroll** [comment]
Namoku, I reported this same issue to the server admin on the server I play on and they discovered that Oreo, who develops resourceful bees, is aware of both issues and has said so on the discord. For the guardian bee its because guardians have the biome set as ocean but there is a general interfering blacklist applied to all bees for ocean which means they dont spawn.

As for mana bees, there is a specific setting you need to change in order to allow them to spawn in the enchanted BYG biomes. I dont remember what it is exactly but if you ask in the resourceful bees discord, im sure they will be able to tell you.

**Comment by Pdiddy973** [comment]
Fixed in 1.3.9 , you will need to re gen new chunks to find them
