### ISSUE TITLE
Need help updating server version

### ISSUE THREAD

**Issue by craveful** [AllTheMods/ATM-6#646]
Hello, I currently have the 1.3.5 version of ALLTHEMODS 6 but I want to update to the most recent version of the server files which is 1.3.7. Can someone show me a step by step guide on how to update servers?

**Comment by Ike-l** [comment]
you should wait, the current version has a bug that prevents people from joining :/

**Comment by thevortex** [comment]
@Ike-l just because you have an issue does not mean the current version is broken, we have 3 servers running this pack, all running the current version, updated the other day, that have plenty of people still able to join. 

@craveful 

Updating your Server
1. BACKUP.
2. Run the server files.
3. Approve the EULA.
4. Turn off your server and access the files.
5. Delete the folders Mods, Configs, Scripts/kubejs, Libraries and the forge jar.
6. Upload the new generated Mods, Configs, Scripts, Libraries and the forge jar to your server.
7. Start Server.
