### ISSUE TITLE
Recipe's Missing

### ISSUE THREAD

**Issue by SquidNeko** [AllTheMods/ATM-6#650]
Recipes missing. Will update as i discover more unless Issue is closed.

Mekanism:
Anchor Upgrade

Pams Harvestcraft 2:
Silken Tofu

**Comment by Dextathelsot** [comment]
Another missing recipe:

Applied Energistics 2:
Cable Facade

**Comment by Pdiddy973** [comment]
the anchor upgrade i believe is disabled, the pack wants you to only use FTBchunks/the map for chunk loading, and the cable facades do work, its a block in the middle with 4 facades around it

**Comment by Gargosch** [comment]
Oh ok, then it does just not show up in JEI

**Comment by Pdiddy973** [comment]
no, if it did it would show all of the different possible options and would clutter JEI with hundreds of cable facades

**Comment by SquidNeko** [comment]
If Anchor is disabled, i would like to request that we get to choose ourself what kind of Anchor mod we want to use.
Also i hiding facades makes people unable to see what the recipe is. 1 Point of Jei is to be able to find the recipe of the item you wanna craft. Clutter is just part of it. So please dont just hide recipe's that still works.

**Comment by Pdiddy973** [comment]
most chunk loaders were disabled in favor of just using one, the FTB chunks instead of several different mods all having chunk loaders. it also helps servers to limit how many chunks people can claim.

 you can change the configs if you want to enable/disable certain items or features as well.
 
 and the Facades i think were change in AE itself , like i said to de clutter JEI. right now even with a large screen JEI has 30 pages, if all the facade options were show it would likely but at least an additional 20 pages of the same facade, the recipe isn't that hard to remember

**Comment by derrickmehaffy** [comment]
> most chunk loaders were disabled in favor of just using one, the FTB chunks instead of several different mods all having chunk loaders. it also helps servers to limit how many chunks people can claim.
> 
> you can change the configs if you want to enable/disable certain items or features as well.
> 
> and the Facades i think were change in AE itself , like i said to de clutter JEI. right now even with a large screen JEI has 30 pages, if all the facade options were show it would likely but at least an additional 20 pages of the same facade, the recipe isn't that hard to remember

It's a setting in AE exactly, I think it's fine to leave that disabled by default and let the users/admins select if it's enabled.

**Comment by Letoric** [comment]
Recipes aren't missing, they are removed intentionally.
