### ISSUE TITLE
Better harvesting options for farms

### ISSUE THREAD

**Issue by kaweepatinn1** [AllTheMods/ATM-6#664]
A few days ago, my farming setup was working fine, with the cyclic harvester harvesting all the blocks i needed it to. However, this was changed in a fix to make the harvester work _very_ slow. I tried using the new create mod to make a farm, but even though its only a 17 by 17 farm, my tps goes from 20 to 5 (10GB server). It seems that whenever the harvester from create is running (moving and harvesting), it creates a lot of lag, which obviously isn't good

I've looked at the other options, but there aren't many good options that I've taken to. 

I don't know what good farming mods are available in 1.16.3, but if it were possible, could a mod be added that could harvest a farm?

tps shown at text in image. tps only gets worse the longer it runs for. ss taken about only 10 seconds after launch of harvester
![2020-12-24_20 56 29](https://user-images.githubusercontent.com/37656629/103089967-9fe3a880-462a-11eb-80d3-675097868e1b.png)

**Comment by NetMasterFlex** [comment]
Have you tried Industrial Foraging plantar and harvester?  They are anything to look at but do radius planting and harvesting. The mod used to be called Mine Factory Reloaded (MFR) and can be automated using other mods in this pack.

**Comment by xQgamers** [comment]
![image](https://user-images.githubusercontent.com/48310812/103305477-da559880-49d0-11eb-8dbe-2cb51b5b954d.png)
I use hopper botany pots (they auto-harvest and put the output directly into the pipes) with cyclic pipes feeding into a chest, which then feeds into the ME system. This is an entire layer of a chunk, so you can see its compact. Only thing is some people don't like botania that much, so that is the only setback I can think of. Also, it will seem like the pipes don't connect to the pots, but thats ok, it will work.
Semi-automating hopperhooks is something I would recommend if you plan on making your farm as big as this.

**Comment by kaweepatinn1** [comment]
Hopper botany pots was one of the first things I tried making, but botania isn’t something i plan to go much into for a while. Also I boost my farm with growth accelerators so it’s much more efficient to instead make a traditional farm, as growth accelerators help a lot for speed. I will look into industrial foraging and see if it has a good alternative!

**Comment by Nonsanity** [comment]
The Industrial Foregoing Harvester breaks the whole plant, returning seed and essence, and any extra seeds that might be produced. So you need the Planter under the center block of the farm to re-plant the seeds. Both can use range upgrades to be any size you want. If you are doing a large crop of only one plant type, the setup is simple. Just pipe the seeds to the planter.

If you want to do something like one of every Mystical Agriculture seed, a little more care needs to be taken. I use multiple Planters with the smallest range upgrade (1) which makes it 3x3. I lock nine seeds into the slots on the left of the Planter's GUI and set the filter on the AE2/RS exporter attached to the Planter to those same nine seeds. Make sure you have more than two or three of each seed before putting them into the system, or the slots on the right may empty and refill with all the same seed so that it stops planting others. Those slots on the right are not lockable. If they have five or six seeds each to start, then they should never be completely empty as the seeds cycle through the system, effectively locking the slot to that seed. As more seeds are produced, they should all fill to 64 and the excess seeds get stored in your system. (I use max-tier Danks in docks with all the slots right-clicked so they lock to specific seeds and essences, with the excess slots locked to a filler item. That way the storage bus on the Dank can be set to high priority, assuring that all the seeds and such go there, but with the empty slots blocked, nothing else does.)

**Comment by Letoric** [comment]
There are already several harvesting options in game. Free to join the [discord](https://discord.gg/K5FBPYa) and ask in the atm6-general channel for guidance from the community in a more interactive way.

**Comment by lazypc12** [comment]
if your in atm6, there is another item called harvester and its from cycilc. then if you put an item collector next to it, when the harvester makes the items drop, the item collerctor picks them up. doesnt break seeds, use the growth accelerator(S) to make it work faster. the harvester take power, but mid game if you make a solar panel you can have enought power for ever. (im not far enough in this server to get a better picture)
![2021-08-14_00 43 22](https://user-images.githubusercontent.com/88919427/129434321-96c90673-decd-45b1-ab81-a4b060516ce2.png)
