### ISSUE TITLE
[1.3.7] Memory Problems and Crashes 

### ISSUE THREAD

**Issue by jayusaeu** [AllTheMods/ATM-6#678]
We've been having memory problems causing our server to crash, and more often as we have had the server. 

I've tried using our server setting to prioritize reducing memory usage and it's worked to a degree but its not working as well anymore. 

I've linked one of our crash reports, and I could use some help figuring out what the problem is as I'm quite clueless on how to analyze the report. 

Thanks in advance!
[crash-2020-12-26_02.21.37-server.txt](https://github.com/AllTheMods/ATM-6/files/5743479/crash-2020-12-26_02.21.37-server.txt)

**Comment by derrickmehaffy** [comment]
I've noticed some lockups also, takes about 15 to 20 minutes for the server to "free itself" and the steps to try and reproduce the crash are pretty random with one exception, certain parts of the nether.

Wish I knew more to try and find the root cause myself but it certainly isn't the free ram in my case, server has 32 GB on a Dell R630 running in my homelab, ATM6 is only set to use 16GB and nothing else running on the host. (Ubuntu 20.04)
