### ISSUE TITLE
Low server tps 

### ISSUE THREAD

**Issue by kamrantekkit** [AllTheMods/ATM-6#700]
I am trying to find the source of the tps drop on a server. I have a feeling it may be minecolonies but I may be wrong here. I profiled the sever using spark. Any help appreciated trying to understand this log to find the source of the tps drop.

https://spark.lucko.me/#DeSCOwMI24

**Comment by Chocopuffs** [comment]
Have you tried using lag goggles, lag goggles can be good for that.
probably a bottleneck, exploring, redstone signal bottleneck, i dunno.... but lag goggles may help.

**Comment by jeremiahwinsley** [comment]
According to that Spark report, your server is spending 40% of each tick in `thut.essentials.util.PlayerDataHandler.saveCustomData()`. 

If you remove that mod and the issue still persists, post another profiler report, otherwise you'll probably need to talk to the developer of that mod.

**Comment by lucasvanhalst** [comment]
A large part (but smaller than the thut essentials mod) is also due to astral sorcery (`hellfirepvp.astralsorcery.common.util.ASMHookEndpoint.addCustomCollision()`), but that'll be fixed in the next release of astral. See https://github.com/HellFirePvP/AstralSorcery/issues/1585
You could manually update to the latest build on your server, it improved performance a lot for me

**Comment by kamrantekkit** [comment]
Removing thut essentials fixed the tps. I am just going to stick with ftb essentials. Thanks
