### ISSUE TITLE
MaxRam setting in server-setup-config.yaml is not working

### ISSUE THREAD

**Issue by Velajuel121** [AllTheMods/ATM-6#703]
Hi, so I downloaded the Simple-Server-Files-1.3.7 from https://www.curseforge.com/minecraft/modpacks/all-the-mods-6/files
I worked my way through the server-setup-config.yaml file and changed the maxRam setting from 5G to 14G and started everything with the bat file.
It automatically downloaded everything and started the server successfully but as im joining on the server normally a minecraft server takes all the RAM it can gets especially a modpack at this size.But on the pc/server there is only a total amount of about 7-8 GB in use. Btw the server has 16GB RAM.
![image](https://user-images.githubusercontent.com/32167792/103415044-c51f6c00-4b80-11eb-85ba-ec2c517db220.png)

So I guess the maximum ram is still on 5GB.

![image](https://user-images.githubusercontent.com/32167792/103415014-a7ea9d80-4b80-11eb-9a60-9674cdddc93a.png)

**Comment by deejaypro** [comment]
Thats because this only defines how much it **can** use overall. 
Java wont allocate that much, because the start server script uses this parameter for the Xmx argument. 
The script then takes this value, devides it by 2 and this is the value it allocates at startup until it needs more (Java Xms argument).
If you want the server to allocate all the memory at startup you need to set a javaArgs that is like the following:
`	- "-Xms14G"`
