### ISSUE TITLE
Server crashes on player login when at specific location

### ISSUE THREAD

**Issue by DraTrav** [AllTheMods/ATM-6#769]
**Describe the bug**
the server crashes when a certain area is loaded
**To Reproduce**
1. Go to the location
2. Server crashes

**Expected behavior**
It not to crash

**Additional context**
https://gist.github.com/DraTrav/1b32acaf6fa6f50b690b2d659bc90579

**Comment by mkaito** [comment]
Please upload the log as a gist rather than an attachment.

**Comment by DraTrav** [comment]
> Please upload the log as a gist rather than an attachment.

Sorry about that. Here it is uploaded as a gist

https://gist.github.com/DraTrav/1b32acaf6fa6f50b690b2d659bc90579

**Comment by mkaito** [comment]
That looks like it might be a problematic tile entity from Pneumaticccraft (not their fault, probably).

You could try to work around this by setting `removeErroringTileEntities = true` temporarily in `world/serverconfig/forge-server.toml` and restarting the server. You probably want to set it back to false once the issue is resolved though.

**Comment by DraTrav** [comment]
I didnt get the chance to do that but I reset the problematic chunk and its fixed
