### ISSUE TITLE
[1.3.9b] Memory leak 

### ISSUE THREAD

**Issue by jeremiahwinsley** [AllTheMods/ATM-6#789]
**Describe the bug**
Pack version 1.3.9b, with 8 GB assigned to the pack. I have reproduced this on both MultiMC and GDLauncher instances.

After about 30 minutes with a world open, I start getting GC spikes/freezes, ~5 seconds unfrozen followed by ~10 seconds frozen. Without the bug, GC triggers at about 80% heap usage, with the bug it reaches 99%.

Exiting to the main menu and rejoining the world does not stop the freezes, they continue to occur during world loading and after it's loaded.

**Comment by jeremiahwinsley** [comment]
Heap dump taken at ~96%: https://drive.google.com/file/d/1qhpnTyOoQhwc6ybA9oFRFsXn2_vFNs0q/view?usp=sharing

**Comment by delta2k** [comment]
Have the same exact issue around about the same time. restart only fixed for about 30mins again.

**Comment by jeremiahwinsley** [comment]
Still getting this on 1.4.0.

**Comment by Raffia16trh** [comment]
Still an issue on 1.4.1 using a wall of jvm arguments to try and mitigate this but its a hit or miss with every relaunch of the game

**Comment by whatthedrunk** [comment]
Let me know if this is still an issue on 1.5.0. Also try Java 11 if you can.

**Comment by AbdulMuqsit** [comment]
Still an issue on 1.5.2

**Comment by Raffia16trh** [comment]
> Still an issue on 1.5.2

@AbdulMuqsit This is an issue with Javas garbage collection breaking. its not exactly the fault of the modpack itself. try giving this wall of java arguments a shot its been keeping my memory from going out of hand. Also make sure your Chisel and bits mod is up to date. since no new items are added in the med running a newer version than the server wont matter.

-Xms8G -Xmx8G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs/ -Daikars.new.flags=true

**Comment by leagris** [comment]
Still an issue in 1.7.6, and **no, it is not the fault of the garbage collector but some mod having cascading worldgen leaking memory**

Please re-open.

**Comment by Zevell** [comment]
I'm having this issue on 1.8.14. I visually see memory usage hit 99% (via F3 statistics) and then the game freezes for roughly 5 seconds. The memory usage goes back down, and it climbs again.
