### ISSUE TITLE
No AllTheOres spawning

### ISSUE THREAD

**Issue by Seanthebaker** [AllTheMods/ATM-6#850]
**Describe the bug**
No ores from AlltheOres are spawning.
Tried using different world generations but none providing them.
Eidolon is still spawning Lead Ore but none of the other ore is available.

**Expected behavior**
All ores in from the mod are supposed to spawn.

**Comment by thevortex** [comment]
Need some logs and copy of your alltheores-common.toml config file plz pastebin.com

**Comment by Seanthebaker** [comment]
Here is the alltheore-common.toml https://pastebin.com/0PumfCEL

hopefully this worked but the "latest" log file was too big for pastebin
[latest.log](https://github.com/AllTheMods/ATM-6/files/5822509/latest.log)

**Comment by thevortex** [comment]
seeing that you have optifine and an older version of all the ores. optifine breaks a lot of worldgen on older versions. update to the newest version of the pack, update optifine to its newest version(they have since corrected whatever was going wrong) and try creating your world again(or if you want to keep that world you will need to venture into new chunks for worldgen to resume correctly.

follow up after completing these steps and let me know how it goes, i will keep the issue open until then

**Comment by Seanthebaker** [comment]
Updated to pack version 1.4.0
Updated Optifine to preview HD_U_G6pre12

AllTheOres Ores are now spawning but I've noticed that Eidolon is spawning its own Lead Ore, wasn't sure if that was by design or just a missed config

**Comment by thevortex** [comment]
yes thats a missed config, we'll get that corrected next update

**Comment by whatthedrunk** [comment]
added the lead note to our Project notes for next update thanks.
