### ISSUE TITLE
1.4.1 Exception in server tick loop Crash 

### ISSUE THREAD

**Issue by backtoback23** [AllTheMods/ATM-6#912]
[crash-2021-01-21_15.49.25-server.txt](https://github.com/AllTheMods/ATM-6/files/5852427/crash-2021-01-21_15.49.25-server.txt)

This is the crash report. Again I can load the mod pack and get to the menu, but when i try to load onto my world it says not responding and crashes.

**Comment by Cntrldfusion** [comment]
looks like a problem loading the config file for Extra Disks mod, check their site to see if there is an issue like this reported

**Comment by backtoback23** [comment]
Hey thanks for the suggestion. I completely removed the mod, then i tried to load my world and it still crashed, with the same crash report also.

**Comment by Cntrldfusion** [comment]
I didn't look into it too much last night but after your reply I looked a bit more.  Extra disks doesn't have a config file in the config directory, it creates one in the serverconfig directory in your world folder on the server.  Thats the file its having a problem with. You may want to check the permissions or since its a .toml file make sure its not corrupted.  Or you could just delete it and and then when you start the server back up it should create a new one.

**Comment by whatthedrunk** [comment]
Install a fresh server and client and make sure to use the supplied configs. If you are still having an issue on 1.5.0 let us know.
