### ISSUE TITLE
Server Crash on startup ATM6 1.5.0/Possibly rats? 

### ISSUE THREAD

**Issue by SquishyBunBun** [AllTheMods/ATM-6#990]
Version 1.5.0, although the issue exists on the 1.4.1 server files that were backed up before trying to update. Server doesn't make it past the startup process, have the crash log here. At one point I managed to delete the specific block entity that was ticking and it found another hopper at a different coordinate that caused the crash. Not sure how to remove/disable all hoppers in any world editing software, maybe I have to go through and manually delete blocks until there are no more error messages? Would like some explanation and help if this is a bug with the files or entirely on my end. 

[crash-2021-02-01_18.00.50-server.txt](https://github.com/AllTheMods/ATM-6/files/5907467/crash-2021-02-01_18.00.50-server.txt)

**Comment by Firerayn** [comment]
Rats seems to cause a lot of issues in 1.5. The server im currently playing on literally crashed every 5 minutes because i was having some rat cages and a rat tube. The log stated an issue with class calling.

This seems to be the same issue with a different item/block from rats. Its the Trash Can. So for now, ask whoever is using it, to remove it. Normal use of the can worked fine so far and even automating it using rats from what i can tell, so my best guess would be someone trying to hopper items into a trash can could cause this issue.

If you can remove items from the map, better remove trash cans than hoppers, the amount of people using hoppers probably is higher than trash can users.

**Comment by scorpion451** [comment]
Also seeing a lot of apparently Rats-related issues in both 1.5 and 1.5.1

For me, I can load my single player world, but various Rats items and entities (it's inconsistent which ones) will be missing textures, I experience significant processor load (normally the game sits around 10%, now I'm seeing consistent 25-50%), and the game crashes fairly quickly.

Two of those crashes have generated logs, the first when I attempted to trade with a plague doctor, the second just walking around (that one seems to be related to an attempt to load a rat wearing a santa hat)

On the processor load: taking down my hopper/trashcan setup possibly made a small difference here, but I suspect the numerous plague doctors with attendant rats around my base aren't helping. (There are usually about 6 to 8 of them loitering at any given time, despite my best efforts to dissuade them.)

**Comment by exastencil** [comment]
I had the following happen: I was on 1.5.1 and played with Rats working fine in the evening. Next morning I launched the game and it ran, but clearly all Rats-related items had no textures loaded (everything was black and purple) and after a few minutes the game crashed. Thereafter it would crash upon loading every time. I disabled Rats and I could launch the world again. I haven't re-enabled Rats, yet.
